# Proyecto del Capítulo de asuntos S&A incluidos los Climáticos - RIOCAS

> Fuente: data/pdfs/Proyecto del Capítulo de asuntos S&A incluidos los Climáticos - RIOCAS.pdf

---

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

1 

## **PROYECTO DEL CAPÍTULO DEDICADO A LAS PRÁCTICAS, POLÍTICAS, PROCESOS E INDICADORES EN RELACIÓN CON LOS ASUNTOS SOCIALES Y AMBIENTALES, INCLUIDOS LOS CLIMÁTICOS** 

A continuación, Riopaila Castilla S.A. presenta la información solicitada por la Superintendencia Financiera de Colombia, teniendo en cuenta que la compañía está clasificada como Emisor Grupo C, lo que significa revelar la información señalada en el **subnumeral 5.1.1.1** del Anexo 2 de la Circular 031 de 2023. Siendo facultativo para los Emisores Grupo C incluir la información señalada en los subnumerales 5.1.2, 5.1.3. y 5.1.4. del Anexo. 

Esta versión actualmente es sometida a derecho de inspección y sólo hasta el día de la Asamblea Ordinaria de Accionistas, prevista para el 26 de marzo, se tendrá documento definitivo y aprobado por los señores Accionistas. 

## **1. MENSAJE DEL PRESIDENTE Y LA JUNTA DIRECTIVA** 

**(GRI 2-22)** 

El 2025 puso a prueba nuestra capacidad de adaptación y la de toda la agroindustria de la caña en Colombia, pues como sector tuvimos que afrontar profundos retos como el aumento de los costos laborales y las tasas de interés, menor productividad del campo, volatilidad de los precios internacionales del azúcar, revaluación del precio frente al dólar, presiones inflacionarias sobre los costos de insumos estratégicos, variabilidad climática, desaceleración del consumo interno, entre otros. 

En este entorno desafiante y a pesar de nuestro esfuerzo, la disciplina operativa y el compromiso de nuestro equipo humano, cerramos un año en el que no alcanzamos los resultados proyectados, ni las metas definidas en la estrategia. Sin embargo, esta realidad, lejos de desmotivarnos, nos brindó una perspectiva clara: **debemos acelerar los procesos de transformación, fortalecer nuestras capacidades y continuar modernizando el modelo de negocio para responder con resiliencia y competitividad.** 

Lo más valioso es que contamos con los pilares fundamentales para hacerlo. Disponemos de un talento humano comprometido, experto y profundamente orgulloso de lo que representamos como empresa; contamos con la materia prima suficiente para avanzar en las metas de molienda y mantenemos un capital estratégico que nos permite seguir invirtiendo en sostenibilidad, innovación y productividad. 

Como agroindustria debemos continuar trabajando en mecanismos que aumenten la productividad y mejoren la rentabilidad de toda la cadena de valor (cluster), es decir, con la participación activa de proveedores de caña, proveedores de obras y servicios, ingenios, entre otros. 

Este Informe de Sostenibilidad y Gestión 2025 refleja, con transparencia, nuestros avances, aprendizajes y desafíos. Presenta los esfuerzos que realizamos para contribuir al desarrollo del país, fortalecer la relación con nuestras comunidades, gestionar de manera responsable los recursos naturales y avanzar en las transformaciones necesarias para cumplir con nuestra estrategia de largo plazo. 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

2 

Somos conscientes que los desafíos del entorno continuarán, pero también sabemos que tenemos la determinación, la capacidad técnica y el talento para honrar, en conjunto con nuestros grupos de interés, nuestro propósito: cuidar el planeta, generar progreso y endulzar el desarrollo de Colombia. 

**Pedro Cardona López** Presidente Ejecutivo Riopaila Castilla 

## **Junta Directiva** 

## **2. MATERIALIDAD** 

**(GRI 3-1) (C 012   7.4.3.3.2) (C 031   5.3)** 

Desde 2024, en Riopaila Castilla desarrollamos el análisis de doble materialidad con el propósito de identificar, evaluar y priorizar los impactos, riesgos y oportunidades en sostenibilidad a lo largo de nuestra cadena de valor. Este ejercicio se realizó con base en las metodologías y lineamientos de estándares, marcos e índices de referencia como Global Reporting Initiative (GRI), European Financial Reporting Advisory Group (EFRAG) y Dow Jones Sustainability Indices (DJSI). 

El proceso contó con el acompañamiento de una firma externa experta, Anthesis, seleccionada para aportar rigor técnico, objetividad y transparencia en la construcción del análisis. 

Iniciamos el ejercicio con un análisis de contexto que incluyó la revisión del entorno regulatorio, macroeconómico, tecnológico, social y político, así como de las principales tendencias de los sectores en los que participamos (alimentos, agricultura, ganadería y refinería). De manera complementaria, revisamos nuestra estrategia corporativa, las megametas 2030 y el análisis de riesgos del negocio, con el fin de identificar impactos, riesgos y oportunidades en sostenibilidad asociados a nuestra operación y cadena de valor. 

La identificación y priorización de asuntos se basó en información interna, expectativas de grupos de interés y referentes sectoriales, lo que permitió construir y validar la Matriz de Materialidad alineada con la estrategia corporativa y los riesgos del negocio; este enfoque considera la magnitud y probabilidad de impactos económicos, ambientales y sociales, así como riesgos y oportunidades para la cadena de valor, orientando la gestión y divulgación en los temas más relevantes para la sostenibilidad y la generación de valor a largo plazo. 

## **(GRI 3-2)** 

|**Asunto**<br>**material**|**Dimensión**|**Razones que sustentan la materialidad**|
|---|---|---|
|**Agua**|Ambiental|El agua es un recurso estratégico para la industria, con riesgos<br>asociados a su disponibilidad, calidad y al aumento de los costos<br>regulatorios. Por ello, es prioritario diversificar las fuentes de<br>abastecimiento, optimizar su uso e incorporar tecnologías y procesos<br>eficientes que permitan reducir la huella hídrica a lo largo de la cadena<br>de valor.|
|**Cambio**<br>**climático**|Ambiental|La gestión del cambio climático mediante planes de mitigación y<br>adaptación es clave para asegurar la continuidad operativa, la<br>disponibilidad de materia prima, el cumplimiento normativo y la<br>competitividad del negocio. Estas acciones permiten gestionar riesgos|

3 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

|||físicos y de transición, reducir la huella de carbono y fortalecer la<br>sostenibilidad integral de la operación.|
|---|---|---|
|**Desarrollo**<br>**territorial**|Social|El desarrollo territorial se gestiona a través de iniciativas que promueven<br>el empleo, las alianzas locales y el relacionamiento con las comunidades<br>del entorno. Mantener canales de comunicación transparentes y atender<br>de manera oportuna los temas ambientales y sociales es fundamental<br>para una convivencia armónica y el fortalecimiento de la licencia social<br>para operar.|
|**Abastecimiento**<br>**responsable**|Económica|La gestión responsable de la cadena de suministro es esencial para<br>mitigar riesgos ambientales, sociales y operativos. El trabajo colaborativo<br>con proveedores, el acompañamiento continuo y la verificación del<br>cumplimiento de estándares y certificaciones permiten asegurar el<br>abastecimiento sostenible y fortalecer la confianza en la cadena de valor.|
|**Agricultura**<br>**regenerativa**|Ambiental|La agricultura regenerativa y la salud del suelo son claves para la<br>productividad y la resiliencia del sistema productivo. Estas prácticas<br>mejoran la eficiencia en el uso de recursos, reducen costos, conservan la<br>biodiversidad y aseguran el abastecimiento de materia prima en el largo<br>plazo.|
|**Crecimiento**<br>**económico**|Económica|El crecimiento económico es un habilitador de la generación de valor<br>económico, social y ambiental. La rentabilidad permite realizar<br>inversiones estratégicas en asuntos materiales, impulsar el empleo,<br>fortalecer el posicionamiento de la marca y acceder a nuevos mercados.|
|**Innovación y**<br>**tecnología**|Económica|La innovación y la tecnología permiten mejorar procesos, optimizar el uso<br>de recursos y diversificar el portafolio de productos. A través de la<br>investigación y el desarrollo, la compañía genera eficiencias operativas,<br>responde a las tendencias del mercado y fortalece su competitividad.|

## **3. NUESTROS GRUPOS DE INTERÉS** 

**(GRI 2-29)** 

La participación de los grupos de interés busca identificar y gestionar asuntos que impactan la relación con el negocio; mediante el diálogo con accionistas, aliados, autoridades, clientes, comunidades, trabajadores, gobierno y sociedad civil, trabajamos en mitigar riesgos y fortalecer nuestra estrategia de relacionamiento, reputación y posicionamiento a partir de temas comunes que generan valor compartido. 

Consulte el detalle de nuestros grupos de interés y las dinámicas de comunicación con cada uno de ellos aquí: https://app.powerbi.com/view?r=eyJrIjoiNmYyOTM4OTAtNjMxNy00MGM2LWE3ZTktZjc1NWFmN2Z mYTc5IiwidCI6IjI3MWRmNTg0LWFiNjQtNDM3Zi04NWI2LTgwZmY5YmVmNmM5ZiIsImMiOjZ9 

## **Compromiso con nuestros inversionistas y accionistas** 

**(C012   7.4.3.3.1)** 

Aseguramos un trato equitativo a todos nuestros inversionistas y accionistas, independientemente de su tamaño o tipo de participación, de acuerdo con lo establecido en nuestro **Código de Mejores Prácticas Corporativas** (numeral 2.4.1). Nuestros administradores y colaboradores velan por el ejercicio pleno de sus derechos y por la atención oportuna de peticiones, reclamaciones y propuestas. 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

4 

Para garantizar el acceso a información relevante y transparente, disponemos de diversos canales de comunicación, entre ellos nuestra **página web corporativa** , la Secretaría General, la Asamblea y la Junta de Accionistas, así como publicaciones periódicas y reuniones informativas anuales. 

## **4. DESEMPEÑO AMBIENTAL** 

## **4.1 Manejo del agua** 

## **(GRI 3-3; 13.7.1)** 

El agua es uno de los pilares estratégicos más relevantes para nuestra operación. Históricamente hemos reconocido su valor como recurso compartido y esencial; por ello, hemos implementado prácticas de uso eficiente y alianzas territoriales para protegerlo. Este compromiso sostenido refleja nuestra comprensión profunda de que el agua no solo sostiene la productividad agrícola e industrial, sino también los ecosistemas y el desarrollo social del territorio donde operamos. 

El Estudio Nacional del Agua del IDEAM advierte que Colombia enfrenta crecientes retos en disponibilidad, calidad y presión sobre el recurso, incluso en zonas tradicionalmente consideradas ricas en agua. Este informe resalta la urgencia de avanzar hacia una gestión más inteligente y preventiva para enfrentar riesgos de desabastecimiento asociados al cambio climático y al aumento de la demanda. Este panorama coincide con las alertas globales del Foro Económico Mundial, cuyo _Global Risks Report_ 2025 identifica que los riesgos ambientales  especialmente los fenómenos climáticos extremos y las crisis de recursos naturales como el agua  ocupan los primeros lugares entre las amenazas más severas de la próxima década. El agua se ubica en el centro de los riesgos globales por su relación directa con desastres naturales, la seguridad alimentaria, la estabilidad económica y el bienestar humano. 

Frente a este contexto, el agua es para nosotros un habilitador estratégico, especialmente con la eficiencia en el uso de recursos, la innovación tecnológica, la resiliencia operativa y la creación de valor compartido. Este enfoque se alinea plenamente con los Objetivos de Desarrollo Sostenible (ODS) 6, 12 y 13, reafirmando que asegurar el agua significa asegurar el futuro de la operación, de las comunidades y del territorio. 

## **4.1.1 Gestión y principales resultados** 

## **(GRI 13.7.1)** 

Nuestra gestión del agua se basó en un enfoque integral que combina políticas internas, eficiencias operativas, adopción de tecnologías y alianzas estratégicas. Los programas de Ahorro y Uso Eficiente del Agua (PUEAA) orientan las metas y acciones para el uso responsable del agua tanto en fábrica como en campo, mediante sistemas de recirculación, control operacional y tecnologías para la medición de caudales. En agricultura mantenemos y ampliamos el uso de riego tecnificado según las condiciones en terreno lo permitan, el balance hídrico como herramienta de programación del riego y prácticas regenerativas como el uso de residuos de caña para mejorar la retención de humedad del suelo. 

En el territorio, mantenemos la contribución con siete Asociaciones de Usuarios de Ríos que operan en Valle y norte del Cauca, así como en mesas técnicas sectoriales con Cenicaña y Asocaña; impulsando la innovación y la colaboración para el manejo responsable del recurso. 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

5 

## **4.1.1.1 Interacción con el agua como recurso compartido** 

**(GRI 303-1; 13.7.2)** 

Gestionamos el agua residual en los procesos productivos y administrativos mediante sistemas de tratamiento adecuados a cada tipo de efluente. En el Valle del Cauca, recirculamos más del 95% del agua residual industrial tratada y vertimos el remanente cumpliendo la normatividad vigente, mientras que en Vichada tratamos las aguas residuales y las empleamos en el cultivo como acondicionador de suelo conforme a los requisitos aplicables. Evaluamos los impactos sobre la calidad y disponibilidad del agua considerando efectos actuales y futuros, lo que nos permitió orientar acciones de eficiencia y mejora continua en todas nuestras operaciones. 

## **(GRI 13.7.1)** 

Fortalecimos la gestión hídrica mediante la planificación, el monitoreo de consumos, calidad de efluentes y la implementación de acciones correctivas cuando fue necesario. De manera complementaria, reforzamos el trabajo colaborativo promoviendo la adopción de buenas prácticas ambientales en nuestros aliados estratégicos, mediante espacios técnicos para el intercambio de experiencias y la presentación de resultados positivos obtenidos en nuestros procesos. Extendimos este compromiso a la cadena de abastecimiento mediante auditorías, acompañamiento técnico y espacios de formación con proveedores de bienes, obras y servicios, promoviendo prácticas responsables más allá de nuestras operaciones directas y fortaleciendo un enfoque integral de gestión ambiental en el territorio **.** 

## **4.1.2 Extracción, consumo y vertimiento de agua** 

## **4.1.2.1 Extracción de agua** 

**(GRI 303-1; 13.7.2)** 

El agua continúa siendo un recurso esencial para el desarrollo del cultivo de caña y palma, así como para actividades industriales y administrativas. La extraemos de fuentes superficiales y subterráneas ubicadas principalmente en las cuencas de los ríos Bolo, Fraile, Desbaratado, Bugalagrande y La Paila, en el Valle del Cauca, y en la cuenca del río Meta, en Vichada. 

## **(GRI 303-3; 13.7.4)** 

Consulte el desglose de nuestra extracción de agua por negocio y por zona aquí: https://app.powerbi.com/view?r=eyJrIjoiYzQ4Zjg5ZjItMjE3Mi00ZGM5LTlmYTktMDhjOWViZGQ4M2Yy IiwidCI6IjI3MWRmNTg0LWFiNjQtNDM3Zi04NWI2LTgwZmY5YmVmNmM5ZiIsImMiOjZ9&pageName =69d52cbb6d53c4863500. 

**Disminuimos la extracción en un 45,8% frente a 2024, principalmente en el negocio de azúcar, derivados y energía, como resultado de la planificación del riego basada en el comportamiento de las lluvias lo que redujo la necesidad de usar agua adicional para suplir la necesidad del cultivo. Y en las fábricas de azúcar mantuvimos una recirculación del 97% del agua, lo que permitió recircular 157.000 ML y evitar la extracción de este volumen desde fuentes superficiales.** 

La extracción de agua de la destilería presentó cambios asociados a las fuentes de abastecimiento. La captación de agua superficial disminuyó un 2,1%, mientras que la extracción de agua subterránea aumentó un 47,9%. En conjunto, el volumen total de agua extraída creció un 2,8%, lo que evidenció una mayor participación del abastecimiento subterráneo en la operación. 

6 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

El incremento en la captación de agua subterránea respondió a reposiciones puntuales cuando el Sistema de Acondicionamiento de Aguas Industriales no cubrió la totalidad de la demanda hídrica requerida; en estos casos, el recurso subterráneo se utilizó como fuente complementaria para garantizar la continuidad operativa y la estabilidad de los procesos productivos. De acuerdo con la clasificación de _Aqueduct_ , nuestras operaciones se desarrollaron en territorios con **niveles de estrés hídrico bajo a medio** , por lo que no se reportaron datos de extracción ni vertido de agua en zonas de estrés hídrico. 

En relación con el cultivo de palma de aceite y la Planta de Beneficio, la información fue consolidada a partir de registros operativos y reportes de seguimiento ambiental asociados a las concesiones de agua vigentes. El componente agrícola se abasteció mediante tres (3) pozos profundos, mientras que la Planta de Beneficio operó con un (1) pozo profundo, todos debidamente concesionados. El registro de los volúmenes captados se realizó conforme a los requerimientos regulatorios aplicables. 

## **4.1.2.2 Vertido de agua** 

## **(GRI 303-4; 13.7.5)** 

Consulte el desglose de nuestras descargas de agua por negocio, tipo de destino y tratamiento aquí: https://app.powerbi.com/view?r=eyJrIjoiYzQ4Zjg5ZjItMjE3Mi00ZGM5LTlmYTktMDhjOWViZGQ4M2Yy IiwidCI6IjI3MWRmNTg0LWFiNjQtNDM3Zi04NWI2LTgwZmY5YmVmNmM5ZiIsImMiOjZ9&pageName =69d52cbb6d53c4863500. 

En 2025, determinamos los volúmenes de aguas residuales generadas en los negocios a partir de sistemas de medición instalados en los efluentes o de acuerdo con proyecciones partiendo de mediciones realizadas con equipos especializados. Este enfoque permitió definir y reportar volúmenes de descarga de manera consistente y trazable. 

Los sistemas de tratamiento de aguas residuales son definidos de acuerdo con la naturaleza de los efluentes, la normatividad aplicable y variables del entorno que condicionan las tecnologías; así en la destilería tratamos las aguas residuales industriales mediante un sistema anaeróbico basado en reactores UASB[1] , mientras que las aguas residuales domésticas se gestionaron mediante tanques sépticos con filtros anaerobios. 

En el negocio de ganadería, el agua captada se destinó principalmente al consumo del ganado en abrevaderos y a usos domésticos, por lo que no se generaron efluentes industriales ni descargas puntuales a cuerpos de agua superficiales; las descargas correspondieron al uso doméstico y se dispusieron al suelo mediante campo de infiltración, previa etapa de tratamiento. En este caso, los volúmenes descargados se determinaron de manera indirecta a partir de los registros de captación de los pozos profundos concesionados y del balance hídrico del sistema, aplicando supuestos técnicos conservadores acordes con la naturaleza de la actividad. 

**En la Planta de Extracción de Aceite, los efluentes líquidos industriales son tratados y reutilizados aprovechando las oportunidades de circularidad en el proceso** . 

## **4.1.2.3 Consumo de agua** 

**(GRI 303-5; 13.7.6)** 

> 1 _Upflow Anaerobic Sludge Blanket_ 

7 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

Consulte el detalle por negocio de nuestro consumo de agua aquí: https://app.powerbi.com/view?r=eyJrIjoiYzQ4Zjg5ZjItMjE3Mi00ZGM5LTlmYTktMDhjOWViZGQ4M2Yy IiwidCI6IjI3MWRmNTg0LWFiNjQtNDM3Zi04NWI2LTgwZmY5YmVmNmM5ZiIsImMiOjZ9&pageName =69d52cbb6d53c4863500. 

El consumo de agua se mantuvo por debajo de 1,00 m³/TCM en las fábricas y por debajo de 1.000 m³/ha en campo, consolidando el hito alcanzado el año anterior. 

Respecto a nuestra megameta ambiental, el consumo de agua en campo se ubicó en 37 m³/TCC, superando el valor máximo esperado de 54,92 m³/TCC (Tonelada de Caña Cosechada). Comparado con la línea base 2022, el consumo por hectárea se redujo un 23%, pasando de 1.119 m³/ha a 855 m³/ha. En las fábricas, la reducción fue del 12%, al pasar de 1,07 m³/TCM en 2022 a 0,94 m³/TCM en 2025, ubicándose en el rango del sector. 

Para 2025 nuestra metodología de medición del consumo de agua incluyó mediciones directas y registros operativos para mejorar la precisión de la información. En la destilería y en la actividad ganadera determinamos el consumo mediante medidores de caudal instalados en pozos profundos concesionados. En el cultivo de palma y en la Planta de Beneficio consolidamos mediciones directas diferenciando usos domésticos, agrícolas y de proceso; además, reutilizamos el efluente tratado (POME), lo que permitió reducir la demanda de agua dulce. 

El incremento del 2,8% en el consumo total de agua de la destilería entre 2024 y 2025 se debe principalmente por la ejecución de actividades operativas de alto caudal realizadas durante el periodo. En particular, llevamos a cabo pruebas de eficiencia de las bombas de la red contraincendios y maniobras de mantenimiento preventivo en el sistema de destilación, incluyendo el cambio de la tubería de entrada de vapor vegetal, intervenciones necesarias para asegurar la confiabilidad y continuidad operativa, que demandaron volúmenes significativos de agua y explicaron el aumento observado. 

## **(GRI 13.7.1)** 

En este contexto, y con el fin de gestionar de manera responsable los impactos asociados al consumo de agua, mantuvimos programas de eficiencia hídrica y ahorro que se han consolidado a lo largo de los años. De forma complementaria, fortalecimos nuestras alianzas con asociaciones de usuarios de los ríos, apoyando proyectos de conservación orientados a mejorar la disponibilidad del recurso hídrico en las cuencas, acciones que se describen en mayor detalle en la sección de hábitats protegidos. 

## **4.1.2.3.1 Gestión de nuestros impactos relacionados con el vertido de agua** 

## **(GRI 303-2; 13.7.3)** 

La gestión y el control de nuestros efluentes se realizaron conforme a los estándares establecidos por la normativa ambiental vigente en cada territorio. En el Valle del Cauca aplicamos los criterios definidos en la Resolución 0631 de 2015, mientras que en Vichada cumplimos con lo dispuesto en la Resolución 1256 de 2021 y con las directrices del ICA para el uso de agua tratada como acondicionador de suelos. Estos lineamientos orientaron nuestras prácticas operativas y garantizaron el cumplimiento de los requisitos regulatorios aplicables en ambas regiones. 

## **4.1.2.3.2 Desempeño de nuestros proveedores y aliados** 

## **(GRI 303-4; 13.7.5)** 

Realizamos de manera periódica auditorías ambientales a proveedores de servicios, en las cuales no se han detectado impactos significativos por vertimientos. En cuanto a los proveedores de caña, hemos promovido su participación en el Programa Integra del Centro de Investigación de la Caña 

8 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

(CENICAÑA). Este programa permite evaluar, entre otros aspectos, las prácticas ambientales de cada unidad productiva y elaborar un plan de mejora para el agricultor. Temas como el uso ineficiente del agua y el manejo integral de residuos sólidos y líquidos se abordan dentro de este plan. Al cierre de 2025, se logró diagnosticar y formular planes de mejora para el 59% de nuestra área de cultivo en Manejo Directo. 

## **4.1.2.4 Metas y proyectos a futuro** 

## **(GRI 13.7.1)** 

A corto plazo, el objetivo es mantener un consumo de agua menor o igual a 55 m3/TCC. Mediante la continuación e implementación gradual de proyectos para la tecnificación del riego, acorde con las condiciones técnicas, operativas y propias del área de cultivo, como estrategia para optimizar el uso del agua. 

Para palma, definimos una meta de consumo mensual de 0.9 m[3] /TRFF, lo cual vamos a lograr mediante la ejecución de mantenimientos preventivos y correctivos a la red de distribución, capacitación del personal e implementación de sistemas de control de nivel en los tanques de almacenamiento. 

## **4.2 Agricultura regenerativa** 

## **(GRI 3-3)** 

Reconocemos que la salud de los ecosistemas es clave para el equilibrio ambiental y para los territorios donde operamos, y que la agricultura regenerativa es una herramienta fundamental para su conservación y para el desarrollo del cultivo. 

Hoy enfrentamos desafíos como el cambio climático, la crisis en biodiversidad y la presión sobre los recursos hídricos, que requieren ir más allá del control de impactos. Por ello, impulsamos prácticas de agricultura regenerativa orientadas a conservar y restablecer funciones de los ecosistemas. Estas condiciones son esenciales para el bienestar ambiental y social de los territorios y, a largo plazo, generan entornos más favorables para nuestros cultivos. 

La integración de criterios ambientales y sociales en la gestión agrícola nos ha permitido fortalecer la relación con proveedores y comunidades, anticipar y mitigar riesgos asociados a la degradación de ecosistemas, la variabilidad climática y la disponibilidad de recursos naturales, y avanzar en prácticas agrícolas responsables alineadas con nuestra estrategia de negocio sostenible. A la fecha, no identificamos impactos negativos derivados de la adopción de prácticas de agricultura regenerativa y promovimos su fortalecimiento mediante la comunicación y el intercambio de experiencias con proveedores de caña. 

## **4.2.1 Nuestra gestión eficiente y principales resultados** 

Avanzamos en la construcción de la guía para la producción de caña con enfoque de agricultura regenerativa, en el marco de la alianza con Nestlé y _The Nature Conservancy_ (TNC) y se realizaron visitas conjuntas de verificación en campo que permitieron validar su implementación en una muestra del área de operación. En 2026 esperamos contar con una versión final verificada de esta guía, la cual será una herramienta de referencia no solo para nuestra operación, sino en general para los cultivadores de caña del país. Como principal aprendizaje, destacamos que el proceso ha abierto 

9 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

oportunidades para explorar temas como el almacenamiento de carbono en el suelo, ampliando el alcance ambiental y climático de la iniciativa y fortaleciendo una visión de sostenibilidad de largo plazo del sistema productivo. 

## **4.2.1.1 Transformación del territorio y uso del suelo** 

## **(GRI 13.4.5)** 

En 2025 no realizamos conversiones de ecosistemas naturales para el establecimiento de cultivos de caña de azúcar ni de palma de aceite. Este resultado respondió a nuestro compromiso con la conservación de la biodiversidad y al procedimiento de verificación ambiental y social previa que aplicamos para la vinculación de nuevas áreas de cultivo, las cuales correspondieron únicamente a suelos de ganadería o previamente cultivados. 

## **(GRI 13.4.2; 13.4.3)** 

Aunque no contamos con una certificación formal de Cero Deforestación, avanzamos en compromisos voluntarios y acciones para prevenir la deforestación en toda la operación. En palma de aceite, mantuvimos nuestra participación en el Acuerdo de Cero Deforestación desde 2018 y no realizamos expansiones desde 2013. En azúcar, fortalecimos la verificación ambiental previa y la trazabilidad de la caña que ingresa a nuestras fábricas, y promovimos la adopción de buenas prácticas por parte de proveedores. Complementamos esta gestión mediante el monitoreo en campo y el uso de herramientas cartográficas para identificar cambios en el uso del suelo y asegurar el cumplimiento de nuestras políticas de conservación. 

## **4.2.1.2 Gastos e inversiones ambientales** 

Consulte el desglose de nuestros gastos e inversiones ambientales aquí: https://app.powerbi.com/view?r=eyJrIjoiYzQ4Zjg5ZjItMjE3Mi00ZGM5LTlmYTktMDhjOWViZGQ4M2Yy IiwidCI6IjI3MWRmNTg0LWFiNjQtNDM3Zi04NWI2LTgwZmY5YmVmNmM5ZiIsImMiOjZ9&pageName =d89e30a0d9988a55b1aa. 

Nuestros gastos e inversiones ambientales se concentraron en cinco categorías clave. En conservación del agua, priorizamos proyectos de gestión integral del recurso hídrico, enfocados en el monitoreo y tratamiento de aguas residuales, la optimización de los sistemas de tratamiento, el seguimiento de aguas superficiales y subterráneas, y el uso eficiente, recirculación y reutilización del agua en fábricas y campo. 

En conservación de la biodiversidad, destinamos recursos a acciones de reforestación, protección de áreas de conservación y fortalecimiento de corredores ambientales, apoyadas por monitoreos de flora y fauna y el trabajo conjunto con asociaciones de usuarios del agua. En mitigación y adaptación al cambio climático, enfocamos las inversiones en eficiencia energética, optimización de calderas y fortalecimiento de la cogeneración. Adicionalmente, en economía circular invertimos en prácticas enfocadas en el manejo integral y cierre de ciclos de residuos y subproductos operativos, incluyendo su recolección, disposición final controlada y aprovechamiento; y también destinamos recursos a auditorías, cumplimiento normativo, gestión de emisiones, compensaciones ambientales y acciones de formación y sensibilización ambiental en nuestras operaciones. 

## **4.2.1.3 Gestión de insumos para la producción agrícola** 

**(GRI 3.6.2)** 

10 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

|**Nivel de toxicidad**|**Volumen de pesticidas empleados (m3)**|
|---|---|
|**Extremadamentepeligrosos**|0|
|**Altamentepeligrosos**|0|
|**Moderadamentepeligrosos**|0,51|
|**Ligeramentepeligrosos**|0,007|
|**Pocopropensos apresentar unpeligro agudo**|0,08|

El volumen de pesticidas utilizado disminuyó como resultado de la promoción del manejo integrado de plagas y enfermedades en el cultivo de caña de azúcar. Combinamos el uso de productos químicos únicamente cuando fue crítico con bioinsumos y productos biológicos de menor impacto ambiental, como _Trichoderma_ y extractos vegetales, evitando este año el uso de productos considerados como alto nivel de peligrosidad; lo que nos permitió reducir riesgos para los suelos, los cuerpos de agua, la biodiversidad local y la salud de los trabajadores, y fortalecer la salud natural del cultivo. 

## **4.2.2 Metas y proyectos a futuro** 

En los negocios de ganadería y palma implementamos el aprovechamiento de la biomasa generada durante la extracción de aceite de palma, específicamente fibra y tusa, como estrategia para el mejoramiento de suelos en fincas ganaderas del Vichada. Entre agosto de 2024 y julio de 2025 aprovechamos aproximadamente 4.500 toneladas de raquis maduro, aplicadas en 14,64 ha del predio Arrayanes, destinadas a ganadería. 

De manera complementaria, continuamos con el aprovechamiento de este residuo en el cultivo de palma de aceite, lo que contribuye a la conservación de la humedad y al aumento de la porosidad del suelo. En el corto plazo buscamos certificar nuestro Sistema de Gestión Ambiental de Palma y en la obtención del certificado de Aceite de Palma Sostenible de Colombia (APS), impulsado por Fedepalma. 

## **4.3 Gestión del cambio climático** 

## **(GRI 3-3)** 

El cambio climático continúa siendo para nosotros un asunto estratégico debido a su relevancia sobre la productividad agrícola, la continuidad operativa y la competitividad del negocio. La organización reconoce que la variabilidad climática y los fenómenos extremos exigen acciones anticipadas y estrategias, por lo que el manejo de este tema se ha incorporado como un eje transversal de la estrategia corporativa. 

## **4.3.1 Gestión y principales resultados** 

En 2025 optimizamos operaciones en campo, cosecha y talleres, logrando una mayor eficiencia en el consumo de combustible y reduciendo el uso de diésel respecto al año anterior, adicionalmente, en la fábrica de Planta Riopaila hemos reducido al mínimo el uso de carbón en las calderas, con el objetivo de eliminar completamente este combustible en el corto plazo; estas acciones representaron una disminución de aproximadamente 10 mil[1 ] tCO   e. Las mejoras no solo reducen costos operativos, sino que también disminuye las emisiones de gases de efecto invernadero derivadas de la operación agrícola e industrial y contribuyen de manera directa a nuestros objetivos de mitigación del cambio climático y al avance de la Ruta de Mitigación a 2030 que nos hemos trazado. 

11 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

En paralelo, contribuimos a la adaptación al cambio climático de las comunidades locales mediante iniciativas impulsadas a través del Fondo Concursable Riopaila Castilla Más, que en 2025 apoyó proyectos orientados a la agricultura sostenible, eficiencia hídrica y generación de energía limpia. Estas iniciativas permiten a las comunidades mejorar la gestión de sus recursos naturales, contribuyendo a la sostenibilidad y resiliencia territorial. De manera complementaria, se mejoraron 14 acueductos rurales, promoviendo la protección de cuencas, el uso eficiente del agua y la capacidad de adaptación frente a fenómenos extremos, y se contribuyó en el mantenimiento de caminos rurales lo que favorece la conectividad de las comunidades durante eventos climáticos adversos. Destacamos como principales resultados en el marco de la gestión climática: 

- Certificación de 11.524 bonos de carbono del proyecto Orinoco2, que captura o evita la emisión de igual cantidad de toneladas de CO   , contribuyendo a la mitigación del cambio climático y a la conservación de más de mil hectáreas de bosques. 

- Reducción de aproximadamente 10 mil[1] tCO2e en las emisiones GEI, gracias a la optimización de combustible en campo y talleres alcanzadas en el marco de un proyecto de eficiencia implementado; y la disminución del uso de carbón en la Planta Riopaila. 

- Apoyo a la adaptación al cambio climático en comunidades locales, mediante el Fondo Concursable Riopaila Castilla Más, la mejora de acueductos rurales y mantenimiento de caminos rurales, promoviendo buenas prácticas de agricultura sostenible, eficiencia hídrica y resiliencia territorial. 

## **4.3.1.1 Nuestra huella de carbono** 

Para comparar de manera consistente nuestro progreso en materia de emisiones, seleccionamos el año 2022 como nuestro año base. Este periodo cuenta con información suficiente, completa y verificable para el cálculo de las emisiones de Gases de Efecto Invernadero bajo condiciones de operación normales, lo que garantiza la solidez y confiabilidad de las comparaciones que realizamos en los años posteriores[2] . 

**(GRI 305-1; 13.1.2;305-2;13.1.3;305-3; 13.1.4)** 

||**Emisiones de GEI (Ton CO2e)**|**2022**|**2023**|**2024**|**2025****|
|---|---|---|---|---|---|
||**Directas  categoría 1 (alcance 1)***|161.395|140.197|105.081|97.992|
||**Indirectas (energía)   categoría 2**<br>**(alcance 2)**|1823|1.596|2.116|1.638|
||**Indirectas   categorías 3, 4, y 6**<br>**(alcance 3)**|61.205|68.819|105.450|92.053|
||**Total**|224.423|210.612|212.647|191.683|

*Las cifras de 2024 varían frente al informe anterior porque en ese momento eran preliminares; tras la validación externa se realizaron ajustes y se actualizaron los datos finales. 

**Las cifras de emisiones GEI 2025 son preliminares y podrían presentar variaciones tras la validación externa en marzo 2026. 

|**Emisiones biogénicas de GEI (Ton**<br>**CO2)**|**2022**|**2023**|**2024**|**2025***|
|---|---|---|---|---|
|**Directas  categoría 1 (alcance 1)**|1.026.003|965.184|1.111.485|1.245.712|
|**Indirectas   categorías 3 y 4 (alcance**|||||
|**3)**|**-**|**-**|**-**|**-**|
|**Consolidado  Total**|**1.026.003**|**965.184**|**1.111.485**|**1.245.712**|

* Las cifras de emisiones GEI 2025 son preliminares y podrían presentar variaciones tras la validación externa en marzo 2026. 

> 2 Se ajustan datos de años anteriores considerando que este año se decide reportar GEI solo para la operación Valle en un formulario consolidado. El enfoque de consolidación seleccionado es de tipo operacional e incluye las actividades de Riopaila Castilla, Destilería Riopaila y Riopaila Energía, y se tienen en cuenta las categorías descritas por la ISO 14064-1:2020. 

12 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

Las emisiones de Gases Efecto Invernadero presentan una reducción del 30% respecto a línea base del 2022, alineándose con la proyección de la megameta ambiental hacia el cero neto en 2030. La reducción en 2025 se debe principalmente a menor uso de carbón en la fábrica de Planta Riopaila y a eficiencias en el uso de diésel para la operación agrícola. 

Las emisiones biogénicas presentan un aumento debido al aumento de molienda, lo cual ha requerido un mayor consumo de bagazo para la generación de vapor, esto en línea con las metas de producción que la Compañía se ha propuesto. 

## **- (GRI 305 1; 13.1.2)** 

||**Emisiones de GEI   directas por tipo de**<br>**combustible (Ton CO2e)**|<br>**2024**|**2023**|**2024**|**2025***|
|---|---|---|---|---|---|
||**Consumo de carbón**|84.884|70.606|34.153|25.273|
||**Consumo de diésel**|29.810|22.960|28.411|26.836|
||**Gasolina**|433|474|510|1.387|
||**Consolidad Total**|**115.127**|**94.040**|**63.074**|54.496|

* Las cifras de emisiones GEI 2025 son preliminares y podrían presentar variaciones tras la validación externa en marzo 2026. 

|**Emisiones biogénicas de GEI   directas**|||||
|---|---|---|---|---|
|**por tipo de combustión o degradación**|**2022**|**2023**|**2024**|**2025****|
|**(Ton CO2)**|||||
|**Caña**|98.115|94.885|58.619|**55.456**|
|**Bagazo**|927.888|870.299|1.052.866|**1.190.256**|
|**Consolidado   Total **|**1.026.003**|**965.184 **|**1.111.485**|**1.245.712**|
||||||
|**Otras emisiones de GEI   directas* (Ton**<br>**CO2)**|<br>**2022**|**2023**|**2024**|**2025****|
|**Total de Alcohol, azúcar, derivados y**<br>**energía**|44.009|<br>43.941|37.867|<br>**44.234**|
|**Consolidado3   Total**|**44.009**|<br>**43.941**|**37.867**|<br>**44.234**|

*Incluye emisiones por aplicación de agroquímicos, tratamiento de aguas residuales y demás fuentes con aportes menores. 

**Las cifras de emisiones GEI 2025 son preliminares y podrían presentar variaciones tras la validación externa en marzo 2026. 

## **(GRI 305-2; 13.1.3)** 

||**Emisiones de GEI   indirectas**<br>**asociadas a energía (Ton CO2e)***|**2022**|**2023**|**2024**|**2025****|
|---|---|---|---|---|---|
||**Alcohol, azúcar, derivados y energía**|1.823|1.596|2.116|1.638|
||**Consolidado  Total**|**1.823**|**1.596**|**2.116**|**1.638**|

* Todas las emisiones indirectas asociadas a la energía son calculadas con el método basado en ubicación. 

**Las cifras de emisiones GEI 2025 son preliminares y podrían presentar variaciones tras la validación externa en marzo 2026 

## **(305-3; 13.1.4)** 

|**Emisiones de GEI   indirectas (Ton**<br>**CO2e)***|**2022**|**2023**|**2024**|**2025****|
|---|---|---|---|---|
|**Alcohol, azúcar, derivados y**<br>**energía**|61.205|68.819|105.450|92.053|
|**Consolidado   Total**|**61.205**|**68.819**|**105.450**|**92.053**|

*Estas emisiones corresponden a las categorías 3 (transporte), 4 (productos y servicios que emplea la organización), y 6 (otras fuentes como emisiones fugitivas, producción de insumos, combustión móvil y estacionaria). 

**Las cifras de emisiones GEI 2025 son preliminares y podrían presentar variaciones tras la validación externa en marzo 2026. 

> 3 El enfoque de consolidación seleccionado es de tipo operacional e incluye las actividades de Riopaila Castilla, Destilería Riopaila y Riopaila Energía, y se tienen en cuenta las categorías descritas por la ISO 14064-1:2020. 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

13 

Respecto al año base 2022, las emisiones indirectas aumentaron principalmente por la mejora en la precisión de los datos de las operaciones agrícolas de nuestros proveedores de materia prima, en años anteriores el cálculo se realizaba a partir de proyecciones, ahora tenemos datos de actividad que nos reducen incertidumbre en el cálculo. 

## **4.3.1.2 Nuestra intensidad de emisiones** 

## **- (GRI 305 4; 13.1.5)** 

||**Ratio de intensidad de emisiones**<br>**de GEI (kg CO2e/TCM)***|**2022**|**2023**|**2024**|**2025****|
|---|---|---|---|---|---|
||**Categoría 1 - Alcance 1**|39,87|36,58|24,7|21,83|
||**Categoría 2 - Alcance 2**|0,45|0,42|0,50|0.36|
||**Categorías 3y 4 - Alcance 3**|15,12|17,96|24,82|20,51|

*Incluye los negocios de alcohol, azúcar, derivados y energía 

*La métrica utilizada para el cálculo de la intensidad de las emisiones de GEI es Tonelada de Caña Molida (TCM) (Riopaila + Castilla), los datos utilizados son: 2022: 4.048.032 TCM; 2023: 3.832.272 TCM; 2024: 4.248.534 TCM y 2025: 4.488.187 TCM 

**Las cifras de emisiones GEI 2025 son preliminares y podrían presentar variaciones tras la validación externa en marzo 2026. 

La reducción en la intensidad de emisiones GEI especialmente alcance 1 refleja la reducción de las emisiones como parte de la implementación de la Ruta de Mitigación 2030 y el aumento en la molienda, lo que resulta en una menor intensidad en 2025 respecto a la línea base de 2022. 

## **4.3.1.3 Nuestras iniciativas para la reducción de emisiones (GRI 305-5; 13.1.6)** 

||**Nombre de la iniciativa**|**Descripción de la iniciativa**|**Emisiones de**<br>**línea base (2022)**<br>**Ton CO2e**|<br>**Emisiones**<br>**reducidas***|
|---|---|---|---|---|
||**Control en el consumo de**<br>**carbón**|<br>Mantener el uso de carbón en las<br>calderas de fábrica Riopaila por<br>debajo del 5%|<br>84.884|59.611|
||**Uso eficiente de**|Implementar mejoras operativas|||
||**combustibles en la**<br>**operación agrícola**|para optimizar el uso de diésel en<br>campo|<br>29.810|2.974|
|||Mayor control operacional en la|||
|||fábrica Castilla para reducir las|||
|||cargas de DQO en el efluente que|||
||**Menos carga de DQO en**<br>**los efluentes de fábrica**|es tratado en el sistema de<br>tratamiento de aguas residuales|15.048|2.938|
|||industriales, de esta manera|||
|||reducir las emisiones debidas al|||
|||CH4|||

El año base es el 2022 y todas las reducciones corresponden a emisiones directas (alcance 1). 

*Las cifras de emisiones GEI 2025 son preliminares y podrían presentar variaciones tras la validación externa en marzo 2026. Nota: El cambio en la cifra del año base para la iniciativa de eficiencia en uso de diésel, se debe a que el dato anterior incluía solo una parte de la operación, la cifra que se reporta en este informe es completa para el alcance 1. 

Las reducciones logradas están en línea con la Ruta de Mitigación establecida a 2030, llegando a consumos mínimos de carbón en 2025. 

## **4.3.1.4 Nuestro consumo de energía (GRI 302-1)** 

14 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

La información reportada corresponde al consumo energético total de la organización, que incluye la energía eléctrica y la energía contenida en los combustibles utilizados, como bagazo, diésel, gasolina y carbón, además de la electricidad comprada. En el caso de la energía vendida, reportamos únicamente la electricidad que autogeneramos y comercializamos. Para estimar la energía de los combustibles, utilizamos su contenido energético, es decir, la cantidad de energía que liberan al usarse. Durante 2025 no implementamos iniciativas que generaran reducciones significativas o medibles en el consumo de energía; la gestión se mantuvo bajo los controles operativos habituales y continuamos evaluando oportunidades de mejora para los próximos periodos. 

Consulte el desglose y el detalle de nuestro consumo energético aquí: https://app.powerbi.com/view?r=eyJrIjoiYzQ4Zjg5ZjItMjE3Mi00ZGM5LTlmYTktMDhjOWViZGQ4M2Yy IiwidCI6IjI3MWRmNTg0LWFiNjQtNDM3Zi04NWI2LTgwZmY5YmVmNmM5ZiIsImMiOjZ9&pageName =ff758ec422ea3b9d106e. 

## **4.3.1.5 Implicaciones financieras del cambio climático** 

**(GRI 201-2; 13.2.2)** 

Gestionamos nuestros riesgos mediante un Sistema de Gestión de Riesgos, alineado con ISO 31000 y COSO ERM, que ayudan a identificar, evaluar y monitorear riesgos estratégicos, tácticos y operativos a partir del análisis del contexto interno y externo de la organización, incluyendo los asociados al cambio climático. 

A nivel estratégico identificamos y gestionamos un riesgo climático relacionado con brechas en la planificación y adaptación frente a la variabilidad climática, con efectos directos en nuestras operaciones agrícolas e industriales. Los efectos de este fenómeno en nuestra operación han sido en el corto plazo, paros operativos por falta de caña, disminución de la productividad y aumento de costos, así como en posibles tensiones con comunidades durante periodos de escasez hídrica. 

Para gestionarlo, implementamos planes de mitigación y adaptación enfocados en la gestión sostenible del agua, la inversión en infraestructura de riego y drenaje, y la adopción de prácticas agrícolas resilientes, como la sincronización de cultivos de caña para cosechar en períodos secos y reducir limitantes por lluvia, estas prácticas fortalecen la capacidad del cultivo para enfrentar condiciones climáticas variables. Este enfoque se complementó con la reducción de emisiones, la incorporación del riesgo climático en las decisiones de inversión y el fortalecimiento de alianzas para la conservación de cuencas, al tiempo que avanzamos en oportunidades como la agricultura regenerativa y el uso eficiente del agua para fortalecer la resiliencia del negocio. 

## **4.3.2 Nuestras metas y proyectos a futuro** 

Para el año 2026 el objetivo es lograr una reducción del 40% en las emisiones directas de Gases Efecto Invernadero para la operación de Alcohol, Azúcar, derivados y energía. 

## **4.4 Información adicional TEMAS MATERIALES** 

## **4.4.1 Manejo de agua** 

## **Metodología para la estimación de vertimiento de agua** 

15 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

Aplicamos el coeficiente de retorno definido en el Reglamento Técnico del Sector de Agua Potable y Saneamiento Básico (RAS 2000), adoptado mediante la Resolución 0330 de 2017, para estimar el volumen de aguas residuales a partir del agua captada, considerando pérdidas por evaporación, infiltración y consumos no retornables. Medimos directamente los volúmenes captados mediante caudalímetros instalados en pozos profundos concesionados y, con base en estos registros, calculamos las aguas residuales generadas para usos domésticos y agropecuarios, bajo el supuesto de que correspondieron exclusivamente a descargas domésticas sin mezcla con agua lluvia u otros efluentes. 

En el cultivo de palma de aceite, las descargas reportadas correspondieron a uso doméstico, fueron tratadas mediante sistemas biológicos y posteriormente infiltradas en el suelo; el mayor volumen de agua en campo se destinó a actividades operativas que no generaron efluente directo. En la Planta de Beneficio, los efluentes industriales fueron sometidos a tratamiento secundario en lagunas facultativas y reutilizados para el riego de 15 hectáreas de la plantación, en cumplimiento de la normativa ambiental y de los permisos otorgados por la autoridad competente. 

## **4.4.2 Gestión del cambio climático** 

## **Metodología para el cálculo de las emisiones de GEI** 

Los Factores de Emisión usados para combustibles son los reportados por la UPME en su calculadora de emisiones, las emisiones de óxido nitroso debidas al uso de fertilizantes nitrogenados se calcularon a partir de los Factores de Emisión reportados por el IPCC en 2006 y los Factores de Emisión para el cálculo de las emisiones indirectas debidas al uso de productos se obtuvieron a partir de bases de datos reconocidas cómo _Ecoinvent_ y _Agrifootprint_ . Adicional usamos como soporte la última versión del software SIMAPRO (8.5.2) 

La metodología seleccionada para la elaboración del inventario es la establecida en la NTC-ISO 140641:2020. El cálculo de las emisiones de GEI se realiza a partir de los datos de actividad de la organización multiplicados por los factores de emisión correspondientes. Los factores de emisión (FE) seleccionados siguen los principios establecidos por la NTC ISO 14064-1:2020. 

Respecto a las fuentes fijas de acuerdo con el Protocolo para el Control y Vigilancia de la Contaminación Atmosférica Generada por Fuentes Fijas, el monitoreo de las emisiones atmosféricas se define con base en el resultado de la Unidad de Contaminación Atmosférica (UCA) obtenido en cada medición 

## **(GRI 201-2; 13.2.2)** 

En relación con el efecto del cambio climático en la operación, el principal impacto identificado durante el período evaluado fue la afectación negativa del rendimiento de la caña. 

Durante el año 2025, el rendimiento se ubicó 0,89% por debajo del promedio de los últimos 10 años, registrándose el nivel más bajo del período histórico comparado. Esta disminución impacta financieramente la generación de efectivo (EBITDA) de la operación en $98.958 MM, derivado principalmente de menores eficiencias agrícolas e industriales asociadas a condiciones climáticas adversas. 

El cambio climático, particularmente el incremento en los niveles de precipitación afecta el rendimiento de la caña y la operación de la siguiente manera: 

16 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

- Aumento de lluvias, que genera mayores niveles de cachaza, reduciendo la eficiencia del proceso industrial y afectando la recuperación de sacarosa. 

- Incremento de paros operativos, lo que conlleva mayores pérdidas indeterminadas, mayores tiempos de permanencia de la caña y pérdida de calidad de la materia prima. 

- Cambios de temperatura, que afectan el desarrollo fisiológico de la planta y, en consecuencia, el contenido de sacarosa. Noches más cálidas y días más fríos. 

- Limitaciones en el uso de madurantes, debido a condiciones climáticas no favorables, lo cual impacta directamente la planeación de cosecha y el momento óptimo de corte. También en la efectividad de los madurantes aplicados. 

- Restricciones logísticas en campo, que dificultan la ejecución del plan de cosecha, incrementan tiempos de espera y reducen el rendimiento efectivo. Adicionalmente las labores realizadas en campo en menor calidad en la siembra y levante de la caña. 

En conjunto, estos factores climáticos explican la desviación negativa observada frente al promedio histórico y su impacto económico asociado, resaltando la creciente sensibilidad del rendimiento agrícola e industrial ante condiciones climáticas más variables e intensas. 

## **4.4.3 Información adicional temas de gestión eficiente** 

## **4.4.3.1 Biodiversidad** 

## **Hábitats protegidos** 

## **(GRI 101-2; 13.3.4)** 

En el marco de nuestra Estrategia de Negocio Sostenible, y a través del Plan de Gestión de la Biodiversidad, definimos como objetivo incrementar progresivamente las áreas bajo conservación, priorizando las zonas de Alto Valor de Conservación identificadas en Valle del Cauca, Cauca y Vichada. Nos enfocamos en la protección y manejo de estas áreas, favoreciendo espacios de refugio y movilidad para la fauna. Como resultado, consolidamos **7.938 hectáreas en conservación** , distribuidas en **bosques de galería, bosques de rebalse y bosques secos** . 

Para evitar impactos negativos sobre la biodiversidad, priorizamos el cuidado de las áreas bajo conservación y fortalecimos prácticas de agricultura regenerativa y de precisión, junto con la reducción del uso de insumos químicos. Desarrollamos procesos de capacitación y sensibilización dirigidos a los trabajadores para el cuidado de la fauna en nuestras zonas de operación. En 2025 realizamos el primer Concurso de Fotografía Ambiental, en el que recibimos más de 168 fotografías captadas por trabajadores en campo. 

Frente a los impactos ambientales inevitables asociados a la operación, implementamos medidas de control operacional tales como el uso eficiente del agua, la reducción del uso de agroquímicos mediante control biológico de plagas, la recirculación de agua residual tratada y la adopción de prácticas de economía circular. Estas acciones fueron acompañadas por un monitoreo continuo de fauna silvestre mediante el uso de cámaras trampa y el reporte fotográfico realizado por los trabajadores. A la fecha, se contó con el registro de 255 especies de fauna en las áreas de operación de Valle del Cauca y Cauca, y de 66 especies en la operación de Vichada. Adicionalmente, nos articulamos con la Línea de Vida de la Corporación Autónoma Regional del Valle del Cauca (CVC) para la atención de fauna silvestre encontrada en las zonas de operación que requirió atención especializada. 

En materia de restauración y rehabilitación de ecosistemas, realizamos la siembra directa de 1.143 árboles nativos en áreas de conservación del Valle del Cauca y de 700 árboles en el departamento del 

17 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

Vichada, así como el mantenimiento y seguimiento de 5,5 hectáreas reforestadas con especies nativas en la cuenca del Caño Gavilán. De manera complementaria, a través de alianzas con la Fundación Fondo Agua por la Vida y la Sostenibilidad y las Asociaciones de Usuarios de los Ríos, destinamos voluntariamente $536 millones para la ejecución de proyectos de conservación ambiental en las cuencas donde operamos. En la cuenca del río Fraile, a través de Asofrayle, sembramos 1.204 árboles en la zona media y alta de la cuenca, contribuyendo a la protección de más de 7.000 hectáreas y al fortalecimiento de la red pluviométrica rural (REPRA), y respaldamos programas de educación ambiental y seguridad alimentaria que beneficiaron a más de 550 personas. 

Adicionalmente, a través del Fondo Concursable, apoyamos financieramente el proyecto Guardianes del Frailejón en el resguardo indígena _Kwe'sx Yu' Kiwe_ de Florida, mediante la reubicación, trasplante y siembra de 2.000 frailejones en áreas despobladas. Asimismo, participamos en el proyecto sectorial de conectividad de 890 kilómetros liderado por Asocaña y fortalecimos el trabajo articulado y voluntario con los proveedores de caña para la conservación de áreas boscosas dentro de sus predios. 

## **4.4.3.2 Otras emisiones al aire significativas (GRI 305-7; 13.1.8)** 

|**Otras**<br>**emisiones**<br>**significativas**<br>**al aire**<br>**Unidad**<br>**de**<br>**medida**|**2022**<br>**2023**<br>**2024**<br>**2025**|
|---|---|
|**PM10**<br>Kg<br>**SOx**<br>**NOx**<br>**Total**|470.779<br>578.691<br>634.341<br>372.952|
||24.871<br>113.537<br>51.172<br>401.790|
||94.299<br>211.184<br>824.084<br>287.147|
||**589.949**<br>**903.412**<br>**1.509.597**<br>**1.061.889**|

Las calderas se monitorean a través de mediciones directas en chimenea, mientras que los sistemas de secado de azúcar se evalúan usando de balances de masa. Estos estudios son realizados por laboratorios externos acreditados, en cumplimiento de la normatividad ambiental aplicable. 

## **(GRI 305-6; 13.1.7)** 

A la fecha no hemos identificado en nuestra operación emisiones de clorofluorocarbonos (CFC), hidroclorofluorocarbonos (HCFC), halones o bromuro de metilo. 

## **4.4.3.3 Gestión de residuos y circularidad** 

Nuestra gestión de residuos se orienta en la jerarquía de gestión, priorizando la reducción en la generación de residuos, luego la separación en la fuente, el aprovechamiento y la valorización de los residuos. Durante el periodo de reporte, fortalecimos estas prácticas dentro de la operación, con el fin de aumentar los volúmenes de residuos aprovechados y reducir la cantidad destinada a eliminación, avanzando en el uso más eficiente y circular de los recursos. 

Los residuos peligrosos son dispuestos con gestores autorizados y los residuos aprovechables comercializados con terceros para su transformación en materiales útiles. 

**(GRI 306-3; 13.8.4)** Consulte el detalle de generación de residuos por negocio y composición aquí: https://app.powerbi.com/view?r=eyJrIjoiYzQ4Zjg5ZjItMjE3Mi00ZGM5LTlmYTktMDhjOWViZGQ4M2Yy 

18 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

IiwidCI6IjI3MWRmNTg0LWFiNjQtNDM3Zi04NWI2LTgwZmY5YmVmNmM5ZiIsImMiOjZ9&pageName =b6e9ac4e216eb67da485. 

Entre 2024 y 2025, los residuos peligrosos aumentaron 68,90%, principalmente por el despacho de 1.160 kg de aceite usado almacenado en 2024. Los residuos ordinarios disminuyeron 3,66%, mientras que los aprovechables aumentaron 44,15%, asociados a cambios operativos como el reemplazo de paneles en torres de enfriamiento, la depuración de archivo histórico y el cambio de tuberías durante el mantenimiento de abril. 

## **Negocio Azúcar, derivados y energía** 

Los datos reportados se recopilan a partir de los registros de peso de las básculas asociados a cada una de las recolecciones realizadas durante el periodo de reporte. 

Durante el periodo analizado, evidenciamos una tendencia de mayor aprovechamiento de residuos en la operación, asociada al aumento en la capacidad de molienda de caña, lo cual generó una mayor producción de residuos industriales como la cachaza y el bagazo, destinados a venta o a su aprovechamiento para la generación de energía y la producción de compost. La disminución en la generación de residuos de aparatos eléctricos y electrónicos (RAEE) se explicó por la ejecución, en años anteriores, de un proceso masivo de baja de equipos por parte del área de Informática, proceso que no se repitió en el año de reporte. 

## **Negocio Palma** 

Durante el periodo de análisis, evidenciamos un aumento en la generación de residuos peligrosos frente a años anteriores. Este comportamiento se explicó por (i) dificultades logísticas que impidieron extraer parte de estos residuos durante el segundo semestre de 2024 y (ii) la disposición final de residuos voluminosos derivados del mantenimiento del sistema de control de emisiones, específicamente mangas del filtro de mangas, que por sus características no fueron susceptibles de aprovechamiento. En paralelo, los residuos no peligrosos representaron la mayor proporción del total generado y sus variaciones se asociaron al nivel de producción de la Planta de Beneficio. 

Adicionalmente, implementamos prácticas de separación en la fuente, aprovechamiento y entrega a gestores autorizados, lo que permitió reducir la fracción dispuesta como residuo ordinario y fortalecer la gestión de materiales reciclables y la disposición final. En conjunto, las fluctuaciones observadas respondieron a condiciones operativas, actividades de mantenimiento y factores logísticos del periodo de reporte, sin cambios estructurales reportados en los procesos productivos. 

Los residuos peligrosos y ordinarios en el área de ganadería son contabilizados en la operación del Negocio Palma, que realiza la gestión a través de un gestor externo. Por lo tanto, estos residuos están siendo contabilizados en ese grupo. 

## **4.4.3.4 Residuos desviados de eliminación (GRI 306-4;13.8.5)** 

Las oportunidades de aprovechamiento de residuos son capitalizadas mediante gestores externos o alianzas con asociaciones comunitarias que promueven la educación ambiental entorno al manejo adecuado de los residuos. Nuestro objetivo es reducir la cantidad de residuos que se envían a disposición final, previniendo la generación o aumentando el aprovechamiento.  En 2025 destacamos 

19 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

la alianza con fundaciones locales que permitieron la recuperación y aprovechamiento de 19 toneladas de residuos fortaleciendo de esta manera las prácticas de circularidad en nuestras operaciones. 

Consulte el detalle de los residuos desviados de eliminación por negocio y composición aquí: https://app.powerbi.com/view?r=eyJrIjoiYzQ4Zjg5ZjItMjE3Mi00ZGM5LTlmYTktMDhjOWViZGQ4M2Yy IiwidCI6IjI3MWRmNTg0LWFiNjQtNDM3Zi04NWI2LTgwZmY5YmVmNmM5ZiIsImMiOjZ9&pageName =b6e9ac4e216eb67da485. 

## **Negocio destilería (alcohol)** 

Los residuos aprovechables, incluyen plástico, papel, cartón y chatarra, fueron entregados a un tercero para su reciclaje, mientras que el aceite usado se gestionó a través de un gestor autorizado para su aprovechamiento. 

## **Negocio Azúcar, derivados y energía** 

Los residuos no peligrosos enviados a valorización fueron aprovechados por gestores para su transformación en nuevos materiales, incluyendo plástico, chatarra, caucho, papel, cartón; en el caso del bagazo y cachaza, son residuos reutilizados en la misma operación salvo una fracción del bagazo que es vendido para aprovechamiento de terceros. La información fue recopilada a partir de los registros de peso de las básculas utilizadas en cada una de las recolecciones realizadas durante el periodo de reporte. 

## **Negocio Palma** 

La mayor proporción de los residuos desviados correspondió a residuos no peligrosos aprovechables, como plásticos, papel, cartón, chatarra metálica y residuos orgánicos, los cuales fueron reincorporados a procesos de reciclaje, reutilización o compostaje. Los residuos orgánicos generados durante la extracción mecánica del aceite de palma fueron aprovechados como biomasa en el cultivo, en una proporción directamente relacionada con el volumen de producción del periodo. 

Durante el año reportado no registramos desvío de residuos peligrosos de la eliminación, debido a la ausencia de infraestructura para su aprovechamiento en el área de influencia; por esta razón, estos residuos fueron gestionados exclusivamente a través de gestores autorizados para su tratamiento y disposición final. El aumento observado en los residuos reciclables frente a 2023 se explicó por la entrega en 2025 de residuos aprovechables que habían permanecido almacenados en años anteriores por limitaciones en la disponibilidad de gestores. 

## **5. DESEMPEÑO SOCIAL** 

## **5.1 Desarrollo territorial** 

**(GRI 3-3) (GRI 13.12.1)** 

20 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

La gestión del relacionamiento con comunidades y gobiernos locales es estratégica para la sostenibilidad y continuidad de nuestras operaciones, integrando dimensiones sociales, ambientales y de gobernanza. Esta gestión se alinea con la estrategia corporativa vigente hasta 2025 y con el asunto material de desarrollo territorial, esencial para la licencia social para operar. Para su ejecución, estructuramos tres focos: **Operación responsable con el entorno** , **Territorios en armonía** y **Sinergias para el desarrollo local** , que traducen nuestros principios en acciones articuladas con el territorio. 

En conjunto, estos focos fortalecen las buenas prácticas operativas, promueven el desarrollo local, optimizan recursos y facilitan la articulación con gobiernos y actores locales, generando impactos positivos en las comunidades y en el entorno operativo. 

En 2025 cerramos un ciclo de implementación que consolidó aprendizajes, estandarizó metodologías y sentó las bases de una nueva fase enfocada en fortalecer buenas prácticas, medir impactos, desarrollar capacidades locales y alinearnos con estándares internacionales como GRI, IFC-OCDE y los ODS. 

## **7.1.1 Nuestros Impactos** 

## **(GRI 13.12.1; 413-2; 13.12.3)** 

Avanzamos en la gestión de impactos operativos generando beneficio para las comunidades, mediante el mantenimiento de vías y canales, el mejoramiento de infraestructura rural y el impulso de iniciativas productivas y comunitarias. Estos resultados provienen de un proceso riguroso de identificación y gestión de impactos reales y potenciales, que incluyó acciones de prevención, mitigación y remediación. Gracias a ello, convertimos riesgos en oportunidades de valor social y en un relacionamiento comunitario más sólido. 

||**Causalidad (Impacto negativo**|**  Gestión  Impacto positivo)**|**  Gestión  Impacto positivo)**|
|---|---|---|---|
|**Negativo**<br>**Real**<br>**/potencial**|**Descripción**|**Medidas de**<br>**prevención,**<br>**mitigación y**<br>**remediación**|**Resultados de los**<br>**impactos positivos**<br>**2025**|
|**Impactos**<br>**reales**|Se registraron 21 impactos reales,<br>asociados principalmente a:<br> Movilidad y deterioro de la<br>infraestructura vial.<br> Seguridad vial en tramos<br>compartidos con las<br>comunidades.<br> Afectaciones puntuales a<br>bienes públicos y privados,<br>como cercas y redes de<br>servicios públicos (electricidad,|<br> <br>En respuesta a los<br>impactos identificados,<br>implementamos las<br>siguientes medidas:<br> Mantenimiento,<br>reparación y<br>limpieza<br>permanente de<br>vías durante la<br>operación.<br> Regulación del| Realizamos<br>mantenimiento de<br>vías públicas que son<br>usadas por la<br>operación y las<br>comunidades vecinas.<br>Así mismo se hizo<br>mantenimiento de<br>acequias o canales<br>que previenen riesgos<br>de inundaciones.|
||acueducto e internet).|tránsito mediante||

21 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

|| Se presentaron**dos bloqueos**|controles de| <br>Nos|
|---|---|---|---|
||**temporales de corta**|velocidad y|articulamos e|
||**duración**, los cuales fueron|geocercas.|impulsamos iniciativas|
||gestionados mediante**diálogo**| Socialización de|comunitarias logrando|
||**directo y acciones**|buenas prácticas|impactar|
||**correctivas oportunas**,|operativas con|positivamente a|
||evitando la escalada de|conductores|55.198 personas a|
||conflictos.|propios y|través de proyectos|
|||contratistas.|productivos para la|
||| Atención y|generación de|
||Asociados al tránsito de vehículos|reparación directa|alimentos,|
||y maquinaria pesada,|de daños a bienes|mejoramiento de vías|
||especialmente en:|públicos y|rurales que dinamizan|
|||privados.|la economía y vida|
|| Tramos angostos o zonas| Articulación con|social de las|
||residenciales.|prestadores de|comunidades.|
|| Uso intensivo de vías<br>terciarias y recursos|servicios públicos<br>y activación de| Generamos|
|**Impactos**|compartidos.|pólizas de|articulaciones con|
|**potenciales**| Generación de polvo, barro y|responsabilidad|organizaciones|
||ruido, con posibles|frente a terceros,|comunitarias,|
||afectaciones a la movilidad,|cuando fue|gobierno local y|
||la seguridad vial y la|necesario.|fuerza pública|
||convivencia comunitaria.||impactando a 218|
|| Tensiones comunitarias ante||personas a través de|
||afectaciones reiteradas o||acciones que|
||percepciones de demora en||impactan la cohesión|
||la atención.||comunitaria y las|
||||tradiciones.|

## **7.1.2 Nuestra gestión y principales resultados** 

## **(GRI 13.12.1)** 

El Plan de Relacionamiento con Comunidades y Gobiernos Locales constituye el marco integral mediante el cual gestionamos impactos sociales y ambientales derivados de la operación y promovemos iniciativas de desarrollo territorial. Este Plan se implementa en coherencia con los Principios Rectores sobre Empresas y Derechos Humanos y el enfoque de debida diligencia, orientado a la prevención, mitigación, corrección y remediación de impactos reales y potenciales, así como al fortalecimiento de impactos positivos. 

El plan articuló, mediante nuestros focos estratégicos de manera coherente los proyectos, acciones e iniciativas de gestión territorial, integrando acciones operativas, comunitarias y de articulación institucional, con un énfasis transversal en el diálogo, la participación efectiva y el respeto por los derechos colectivos, como se puede detallar a continuación: 

|**Operación**<br>**Responsable**<br>**con el entorno**|**Territorios en**<br>**Armonía**|**Sinergias para**<br>**el desarrollo**<br>**local**|**De manera**<br>**transversal, el Plan se**<br>**soporta en:**|
|---|---|---|---|
|Gestionar<br>impactos<br>operativos|Promover el<br>desarrollo<br>territorial|Promover<br>alianzas para la<br>sostenibilidad<br>de la operación.||

22 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

|Prevención de impactos potenciales,|  **Espacios**|
|---|---|
|Mitigación, corrección y remediación de impactos reales,|**permanentes de**|
|Fortalecimiento de impactos positivos (cohesión|**diálogo con**|
|comunitaria, inclusión, fomento de la sostenibilidad del|**comunidades y**|
|territorio, refuerzo del tejido social), dinamización social|**gobiernos locales.**|
|y económica comunitaria||
|Articulación, coordinación y/o fortalecimiento con los|  **Mecanismos de**|
|diferentes grupos de interés.|**identificación,**|
|Gestión del<br>tránsito,<br>mantenimiento de<br>vías, control de<br>polvo, reparación<br>de daños,<br>articulación con<br>autoridades<br>Iniciativas<br>comunitarias,<br>productivas,<br>ambientales, de<br>infraestructura<br>Coordinación<br>interinstitucional<br>y comunitaria,<br>apoyo a<br>iniciativas,<br>fortalecimiento<br>de espacios|**monitoreo y**<br>**atención de**<br>**impactos.**<br>  **Articulación con**<br>**actores públicos,**<br>**privados y**<br>**comunitarios.**|
||  **Socialización de**|
|Comunidades locales, productores agrícolas, usuarios|**buenas prácticas**|
|de vías, actores públicos, privados, personal propio,|**operativas con**|
|contratistas y otros grupos de interés.|**personal propio y**|
||**contratistas.**|

**(GRI 13.14.1; 411-1; 13.14.2; 13.14.3; 13.14.4)** 

Nuestro Plan incorpora la **participación de las comunidades indígenas, campesinas, afrodescendientes y población local no perteneciente a grupos étnicos,** en espacios de diálogo, en coherencia con los estándares internacionales de derechos humanos; de esta manera se generan articulaciones que fortalecen iniciativas en los territorios, y mejora de nuestras prácticas de operación. 

En 2025 trabajamos con resguardos indígenas en los municipios de Florida, Valle del Cauca y en Santa Rosalía, Vichada, mediante mejoras viales, acciones de conservación ambiental, apoyo a proyectos comunitarios y fortalecimiento cultural, en coordinación con autoridades indígenas y actores locales. La participación comunitaria fue clave para definir prioridades, hacer seguimiento y validar resultados. Gracias a este trabajo articulado, durante el período reportado no se presentaron incidentes que afectaran los derechos de los pueblos indígenas. 

**(GRI 13.22.1)** 

Fortalecimos las medidas para identificar, prevenir y ajustar prácticas de abastecimiento que pudieran afectar la inclusión económica de productores agrícolas y proveedores locales, especialmente pequeños productores de nuestras zonas de operación. A partir de los aprendizajes del **Fondo Concursable Riopaila Castilla Más** , identificamos barreras para que proyectos productivos comunitarios transitaran hacia esquemas comerciales con la compañía, principalmente por requisitos administrativos, capacidades financieras limitadas y tiempos de pago. Con base en esto, realizamos ajustes internos para facilitar su participación en la cadena de suministro. 

Las principales medidas implementadas fueron: 

- Ajustes en procesos de abastecimiento para reducir barreras de acceso al mercado. 

- Fortalecimiento de esquemas de transición de iniciativas comunitarias hacia relaciones comerciales. 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

23 

- Acompañamiento a productores y proveedores locales en su vinculación a la cadena de suministro. 

Asimismo, impulsamos el fortalecimiento de emprendimientos comunitarios mediante su participación en los **mercados campesinos del programa Compromiso Rural** de Asocaña, ampliando sus redes comerciales y visibilizando sus productos. 

## **7.1.3 Nuestros Indicadores de seguimiento   Inversión social en el territorio** 

## **(GRI 203-1; 13.22.3)** 

Destinamos el **9% de la inversión social** ($1.175 millones) al relacionamiento con comunidades priorizadas, fortaleciendo su desarrollo social y económico y gestionando responsablemente los impactos de nuestra operación. En **Operación responsable con el entorno** , invertimos **365 millones COP** en mantenimiento de vías y acequias, reduciendo riesgos de movilidad e inundaciones. A través de **Territorios en Armonía** , destinamos **578 millones COP** , beneficiando a **55.198 personas** mediante mejoramiento de vías rurales, protección ambiental y proyectos productivos que impulsan la economía y capacidades comunitarias. Finalmente, con **Sinergias para el Desarrollo Local** , invertimos **$232 millones** , articulando esfuerzos con comunidades y autoridades para fortalecer la cohesión social, las tradiciones y el bienestar, impactando a **218 personas** . 

|**Tipos de Inversiones y servicios**<br>**Unidad de medida**|**2022**<br>**2023**<br>**2024**<br>**20254**|
|---|---|
|**Operación responsable con el entorno**<br>Millones COP<br>**Territorios en armonía**<br>**Sinergiaspara el desarrollo local**<br>**Total**|0<br>0<br>231<br>365|
||256<br>384<br>713<br>578|
||453<br>264<br>274<br>232|
||710<br>649<br>1.218<br>1.175|

## **7.1.4 Impactos económicos indirectos significativos** 

## **(GRI 203-2; 13.22.4)** 

Los impactos económicos indirectos son un eje central de nuestra gestión y reflejan nuestro compromiso con el desarrollo sostenible, en coherencia con estándares internacionales, marcos regulatorios nacionales y las expectativas de los grupos de interés. A través de nuestras operaciones, promovemos un crecimiento económico inclusivo que contribuye al bienestar de las comunidades y a la sostenibilidad de los territorios donde operamos. 

|**Número**|**Descripción**|
|---|---|
|**1**|Infraestructural vial: tránsito de maquinaria durante periodos húmedos podría acelerar el<br>desgaste de vías compartidas. (Negativo).|
||Largos periodos de pago a proveedores locales: los plazos extendidos para la liquidación|
|**2**|de pagos pueden generar tensiones financieras en los pequeños proveedores, afectando|
||su flujo de caja y su capacidad para invertir en sus procesos productivos. (Negativo).|
||Disminución de rentabilidad accionistas: el incumplimiento de normativas ambientales o|
|**3**|sociales puede llevar a sanciones o costos adicionales en procesos de mitigación.|
||(Negativo).|

> 4 Territorios en Armonía y sinergias para el desarrollo tuvieron una reducción frente al año 2024, debido a disminución presupuestal en el marco del contexto del sector (precio dólar y del azúcar). 

24 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

||Generación de empleo local indirecto: contratación de proveedores que a su vez|
|---|---|
|**4**|contratan población residente en los municipios de las áreas circundantes a las plantas.|
||(Positivo).|
|**4**|Intervención en infraestructura local: los mantenimientos de las vías pre y postcosecha<br>benefician a las comunidades vecinas de los cultivos. (Positivo).|
|**5**|Dinamización de economía local.(Positivo).|
|**7**|Fortalecimiento de proyectos comunitarios: apoyo a través de inversión o compra de<br>insumos. (Positivo).|
|**8**|Fortalecimiento del tejido social a través del acompañamiento y apoyo a las acciones que<br>promueven las tradiciones y costumbres de la comunidad. (Positivo).|
|**9**|Fortalecimiento de capacidades organizativas en la comunidad.(Positivo).|
||Mantenimiento de vías terciarias a través del programa Caminos Rurales: intervención de|
|**10**|vías donde no transita la operación, pero que dinamiza la economía y la conectividad de|
||comunidades aledañas a las ZOS. (Positivo).|
||Intervención de infraestructura comunitaria:  reparación o reconstrucción de casetas|
|**11**|comunales, escuelas, parques, incorporación de soluciones de energías limpias  como<br>la instalación de paneles solares  para fortalecer espacios colectivos más seguros,|
||sostenibles y resilientes, entre otros. (Positivo).|

## **7.1.5 Operaciones con participación de la comunidad local, evaluaciones del impacto y programas de desarrollo** 

## **(GRI 413-1; 13.12.2)** 

Realizamos el monitoreo de los resultados de las evaluaciones de impacto social y ambiental en las Zonas de Operación Significativa, cubriendo el **67 % de las comunidades identificadas** , priorizando aquellas con mayor interacción con la operación. El **100 % de los resultados** fue divulgado y socializado con estas comunidades, sirviendo como insumo técnico para el Plan de Relacionamiento y la definición de medidas de prevención y mitigación de impactos. 

En materia ambiental, solo la **Destilería Riopaila** está sujeta a una **Evaluación de Impacto Ambiental (EIA)** bajo Licencia Ambiental, lo que representa el **20 % de las operaciones del Grupo** , acorde con las exigencias normativas y los riesgos específicos de cada tipo de operación. 

## **Nuestras iniciativas comunitarias** 

## **(GRI 413-1; 13.12.2)** 

La gestión del desarrollo territorial y del relacionamiento con comunidades y gobiernos locales se materializó en la implementación de proyectos, programas e iniciativas orientadas a fortalecer la continuidad operativa, promover el desarrollo local y generar valor social en los territorios donde tenemos presencia. 

Las acciones desarrolladas se concentraron en el fortalecimiento de economías locales, la mejora de la infraestructura comunitaria y vial, la seguridad alimentaria, la educación ambiental y la articulación con actores comunitarios e institucionales. Los resultados alcanzados reflejan el enfoque estratégico de la organización y su compromiso con una gestión territorial estructurada, basada en el diálogo, la colaboración y la atención de las prioridades del entorno. 

A continuación, se presentan los principales proyectos e iniciativas implementados durante el período, junto con su ubicación, descripción y los logros o hitos más relevantes alcanzados: 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

- En el marco del foco _Territorios en Armonía_ , el Fondo Concursable **Riopaila Castilla Más 2025** apoyó 20 proyectos comunitarios en nueve municipios, beneficiando a más de **18.000 personas** . La iniciativa fortaleció dinámicas económicas, sociales y ambientales mediante proyectos productivos, de infraestructura comunitaria y sostenibilidad. 

- Con una inversión de **192 millones COP** , se impulsaron prácticas como piscicultura comunitaria en Miranda, instalación de paneles solares en zonas rurales de Florida y Bugalagrande, en el Valle del Cauca, y mejoramientos en espacios comunitarios como centros de atención y parques infantiles. También se apoyaron iniciativas ambientales y de economía circular, como _Renaceite_ en Zarzal y proyectos de seguridad alimentaria en Bugalagrande. 

- Se articularon **47 iniciativas** y **222 acciones de sinergia** , impactando a más de **160.000 personas** en educación, infraestructura, fortalecimiento organizativo y medio ambiente. 

- En Padilla (Cauca) se avanzó en la segunda fase de inclusión económica con el SENA y la UMATA, mejorando unidades productivas y la infraestructura educativa de Sololado. Programas como _Huerteritos en Zarzal_ y el proyecto con niños en Miranda fortalecieron la educación ambiental, el manejo de residuos y la cohesión social. Además, se reforestó la cuenca del río La Paila. 

- En **Caminos Rurales** , se mejoraron **145 km** de vías terciarias, beneficiando a más de **8.000 personas** . A esto se sumó el mejoramiento de **326 km** de vías usadas para la operación de la compañía. 

- En alianza con la Fundación Corazón de Caña, se construyó la **Ludoteca de Obando** y se mejoró la caseta comunal de San Antonio de los Caballeros, beneficiando a más de **12.000 personas** . Con Asocaña y _Obras por Impuestos_ , se avanzó en el mejoramiento vial de la quebrada La Alacranera, con una inversión superior a **6.000 millones COP** , favoreciendo la movilidad de comunidades rurales. 

25 

## **7.1.6 Nuestras metas y proyectos a futuro** 

- **A corto plazo (0 a 2 años)** 

   - Apoyar al menos 40 proyectos del Fondo Concursable Riopaila Castilla Más, que promuevan iniciativas comunitarias de cara al desarrollo del territorio. 

   - Alinear e implementar el Plan de Relaciones comunitarias en los Territorios con los Principios Rectores sobre Empresas y Derechos Humanos, los principios de IFC y la OCDE, y los indicadores GRI aplicables, asegurando que estos enfoques se reflejen de manera operativa en la gestión territorial. 

   - Mantener la participación en los procesos críticos de la operación, promoviendo la adopción de buenas prácticas de operación con enfoque social, ambiental y de derechos humanos. 

- **A mediano plazo (3 a 5 años)** 

   - Establecer alianzas estratégicas para fortalecer al menos el 60 % de las iniciativas apoyadas a través del Fondo Concursable, con el objetivo de mejorar su sostenibilidad técnica, organizativa y financiera en los territorios. 

   - Consolidar la medición del Plan de Relaciones comunitarias en los Territorios mediante la articulación con estándares y metodologías reconocidas, como FSA SAI, DJSI, Bonsucro, el Plan de Debida Diligencia en Derechos Humanos, GRI y ejercicios piloto de medición de valor social (SROI). 

   - Actualizar e integrar criterios socioambientales y de derechos humanos en los estándares de los procesos de campo y cosecha, fortaleciendo la coherencia entre la operación y la gestión territorial. 

- **A largo plazo (6 años o más)** 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

26 

- Lograr que al menos el 50 % de las iniciativas apoyadas mediante el Fondo Concursable se mantengan activas en los territorios, evidenciando sostenibilidad y apropiación comunitaria. 

- Consolidar el Plan de Relaciones comunitarias en los Territorios como la materialización operativa de los principios internacionales en derechos humanos, sostenibilidad y conducta empresarial responsable para la compañía. 

- Mantener la sensibilización permanente del personal de campo y cosecha en buenas prácticas de operación, con énfasis en prevención de impactos, relacionamiento comunitario y respeto por los derechos humanos. 

## **7.2 Fundación Caicedo González Riopaila Castilla** 

## **LEGITIMIDAD Y TRANSFORMACIÓN TERRITORIAL EL VALOR DE LA INVERSIÓN SOCIAL ESTRATÉGICA** 

Para el Grupo Agroindustrial Riopaila Castilla, la sostenibilidad trasciende los límites de su operación. Como actor económico del desarrollo, reconoce el vínculo simbiótico que lo une a los territorios donde opera e integra de manera orgánica la Inversión Social Estratégica (ISE) a su estrategia de negocio y a los desafíos sociales del Valle del Cauca y el Norte del Cauca, para consolidar, desde la perspectiva del desarrollo territorial, una plataforma de creación de valor social público compartido. 

La Fundación Caicedo González Riopaila Castilla, con una trayectoria institucional de 68 años, actúa como agente social de desarrollo, catalizador de esta inversión, para impulsar transformaciones sociales sostenibles que contribuyan a mejorar el acceso a derechos de las poblaciones con mayor grado de privaciones o riesgo de vulneración social en los territorios de operación significativa de la empresa. En su gestión, asegura una operación en equilibrio mediante la alineación estratégica; un alto desempeño financiero y operativo integrados; un riguroso sistema de planeación, medición y evaluación e integra en su ejecución los resultados y aprendizajes que le permiten potenciar su capacidad técnica y relacional. 

Convergencias Territoriales es la estrategia a través de la cual la Fundación despliega la inversión social. No responde a intervenciones puntuales. Genera capacidades en los actores públicos, privados y comunitarios que movilizan las dinámicas de participación y articulación urbano-rural, de tal manera que los territorios avancen en el cierre de brechas en asuntos clave de su sostenibilidad; el fortalecimiento de la gobernanza territorial, el tejido social, el mejoramiento de los ingresos y la disponibilidad y acceso a alimentos. Orientada, al fortalecimiento de la autonomía y resiliencia económica de los territorios, promueve la profundización de la democracia, generación y distribución de riqueza e impulsa redistribución a través de la provisión concertada de bienes públicos. 

La gestión de la Inversión Social bajo esta lógica estratégica, garantiza a Riopaila Castilla cimentar una legitimidad que contribuye a la sostenibilidad del negocio y al desarrollo regional, así como una adaptación ágil y pertinente a las dinámicas socioeconómicas y a los desafíos emergentes de sus zonas de operación significativa; atemperándose  de esta manera a enfoques internacionales como la Creación de Valor Compartido   CSV (Creating Shared Value), los Objetivos de Desarrollo Sostenible (ODS), Estándares de Desempeño IFC y los marcos ASG (Ambiental, Social y Gobernanza). 

## **La Inversión Social Estratégica de Riopaila Castilla** 

[GRI 201-1] 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

En 2025, Riopaila Castilla asignó $6.648 millones de Inversión Social Estratégica. 

## **7.2.1 La gestión de la Fundación** 

- **Eficiencia en la Generación de Valor (SROI) 3,9:** Medición externa. Por cada peso invertido, se generan **$3,9** en beneficios tangibles e intangibles para los territorios. 

- **Creación de Valor Social Neto: USD $15,5 millones** . 

- **Apalancamiento** . 38 alianzas estratégicas movilizaron $9.961 millones adicionales en recursos de contrapartida. 

- **Tasa de Recursos Gestionados (TRG) 150%** .  Por cada peso invertido por la compañía, la Fundación gestionó $1,5 adicionales. 

- **Índice de Capacidad Organizativa   ICO 0,86** Medición externa. Evalúa gobernanza, gestión interna, rendición de cuentas y transparencia y gestión externa, refleja alto nivel de credibilidad y transparencia organizacional. 

- **Índice Global de Reputación   IGR 822.** Medición externa. Rango de vínculo racional con grupos de interés 

## **7.2.2 La entrega de valor social:  Convergencias Territoriales y la Construcción Colectiva del Desarrollo** 

##   **Cobertura poblacional** 

-   Población participante 17.405 personas, 17% Indígenas, 15% Afrocolombianos, 67,8% otros, 0,2% ninguno y 4% campesinos 

27 

   -   2.635 familias 

   -   183 organizaciones sociales 

- **Cobertura territorial** , cinco Convergencias Territoriales 

   -   14 municipios del Valle y norte del Cauca, 63% de las Zonas de Operación Significativa de Riopaila Castilla 

##   **Resultados estratégicos** 

-   **Portafolio de inversión territorial:** inversión pública privada y comunitaria,155 proyectos e iniciativas, $32 mil millones. 

##   **Condiciones de Vida** 

   - Acceso y disponibilidad de alimentos 

- 73 especies con producción de 3.744 toneladas de alimentos 

- 165 unidades productivas con productos de valor agregado 

_Acompañamos las trayectorias de desarrollo de los territorios, construyendo desde la confianza y recuperando vínculos históricamente fracturados. Nuestro propósito se concreta cuando los territorios amplían su colaboración, producción, gobernanza y cohesión social._ 

## **La Construcción Colectiva del Desarrollo** 

[GRI 413] 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

28 

**Meta 2030** cinco Convergencias Territoriales en el 70% de la Zonas de Operación Significativas de Riopaila Castilla. 

Nuestro compromiso de impulsar un futuro incluyente, armónico y sostenible para todos orienta Convergencias Territoriales. La comprensión sistémica de los territorios guía nuestro modelo operativo; comprende una caja de herramientas con estrategias de acompañamiento que superan la ruta lineal tradicional, y se soportan en la cocreación, la innovación social y el aprendizaje continuo. 

- **Escuelas de Liderazgo y Redes Comunitarias o Empresariales** para el fortalecimiento del capital social y la capacidad de gestión local. 

- **Asistencia técnica a entes territoriales y agendas ciudadanas,** orientadas a la eficiencia en la gestión de lo público, la alineación de planes de desarrollo con expectativas ciudadanas y empresariales y la concertación de visiones y de asuntos comunes para el desarrollo. 

- **Fortalecimiento de la agricultura familiar y los procesos empresariales** para impulsar encadenamientos productivos sostenibles, generar valor agregado y acceso a mercados. 

_Trabajar con enfoque territorial para la Fundación significa reconocer la singularidad de cada territorio, escuchar sus voces, comprender sus procesos previos y actuar de manera situada, articulada y pertinente._ 

Cada territorio marca la ruta de su futuro bajo una idea de bienestar propia coherente con sus valores, tradiciones y sueños. Ningún territorio es una hoja en blanco, en él se encuentran activos, expresados en capacidades, vocaciones territoriales, liderazgos y procesos colectivos de los que se apalanca la estrategia para desatar trayectorias progresivas y estructurales de transformación social. 

La Gestión Territorial Colaborativa como entrega de valor social se materializa en dos resultados clave: 

**Portafolio de Inversión Territorial** . Como sistema de decisiones colectivas, permite convertir recursos públicos, privados y comunitarios en apuestas coordinadas, pertinentes y autónomas sobre asuntos estratégicos del desarrollo. Las iniciativas y proyectos evidencian una orientación hacia la habilitación de derechos económicos y productivos, $29.382 millones; $4.590 millones para proyectos e iniciativas de derechos sociales y educativos, y $1.392 millones en derechos ambientales, culturales, políticos y ciudadanos. 

**Condiciones de vida** . En el marco de la movilidad social y la autonomía productiva, se consolida la producción de **3.744 toneladas de alimentos y 73 especies diversas,** lo que representa un incremento del **19,2%** y **10,6%** respecto al año anterior. Este hito contribuye a la disponibilidad y el acceso nutricional a nivel local, y constituye la base de la estabilidad económica de las unidades y familias productoras. 

El proceso evoluciona de la producción primaria a la sofisticación técnica, logrando que **165 unidades productivas** avancen a la transformación agroindustrial; lo que permite la disponibilidad de productos procesados, innovadores, con mayor vida útil y mejor posicionamiento en circuitos comerciales locales. 

El desarrollo de estas capacidades productivas y de transformación, son el motor que permite incrementar el ingreso familiar promedio, situándolo en **$2.046.000** , reduciendo la vulnerabilidad frente a las fluctuaciones de precios o escasez de alimentos. 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

29 

Estos resultados, en materia de bienes públicos, ingresos, producción, y transformación de alimentos, se apalancan en transformaciones que emergen del sistema de relaciones territoriales y se expresan de manera diferenciada en las cinco Convergencias Territoriales. 

## **Bugalagrande, de la fragmentación a la gobernanza productiva** 

Bugalagrande, es un territorio con activos estratégicos que lo proyectan como territorio clave para la consolidación de una Convergencia Territorial orientada a la gobernanza y la productividad agrícola, empresarial y comercial; comprende un ecosistema de actores sociales, privados y públicos dispuestos al diálogo y a la construcción colectiva de soluciones para el desarrollo. Sin embargo, durante años este potencial permanecía disperso. La falta de coordinación, la desconfianza entre sectores y la ausencia de espacios estables para tomar decisiones conjuntas, les impedían avanzar como territorio. 

El estallido social, fue el punto de inflexión del que emergió **una juventud decidida a transformar la protesta en propuestas, participación y diálogo.** En ese contexto, impulsamos la **Escuela de Liderazgo,** no como un aula tradicional, sino como **estrategia para reconstruir confianza.** Jóvenes, mujeres y pequeños empresarios se encontraron, escucharon y reconocieron; la desconfianza dio paso al respeto mutuo y a la construcción de propósitos compartidos. 

Surge así la consolidación de la Agenda **Ciudadana** ; concreta su incidencia en la incorporación de **iniciativas en el Plan de Desarrollo Territorial (PDT** ), como resultado de los acuerdos sobre los desafíos más relevantes del territorio para enfrentarlos de manera conjunta con la institucionalidad pública. Adicionalmente, Jóvenes, mujeres, productores campesinos y pequeños empresarios trabajaron articuladamente en la formulación, gestión y ejecución de **iniciativas colectivas de desarrollo** en torno a la producción agrícola, la comercialización local y la cultura, demostrando transformaciones en el liderazgo del territorio. 

El aprendizaje del trabajo colectivo logra la conformación de asociaciones como **ASCAGUAY, AFAMESTIZAL y ASOCALF,** que avanzan de la agricultura familiar de subsistencia al impulso desde una red empresarial autónoma que hoy lidera eventos de alto impacto como el Festival Bugalagrande Tierra de Sabores, y el fortalecimiento de circuitos comerciales locales. 

La institucionalización de la **Mesa Técnica de Inversión Social** formalizó una nueva forma de relacionamiento público-privado, sella esta nueva gobernanza participativa, transparente y orientada al desarrollo. 

Bugalagrande deja un aprendizaje central: cuando existen espacios de confianza, diálogo y corresponsabilidad, los territorios transforman la fragmentación en articulación, y sus activos en oportunidades reales. 

## **Florida, Pradera, Miranda y Corinto, circuitos de resiliencia** 

Esta Convergencia es un escenario estratégico para el desarrollo de esquemas de producción, transformación y comercialización territorial. Su fortaleza está en la organización social de comunidades étnicas, campesinas, mujeres y jóvenes comprometidos con su futuro; instituciones públicas abiertas al diálogo y con capacidad de gestión; y una oferta educativa técnica, tecnológica y superior conectada con las vocaciones productivas del territorio, con una inversión pública y privada sostenida. 

Este potencial convive con grandes desafíos: la fragmentación entre municipios, la baja confianza entre personas e instituciones y un contexto persistente de conflictividad que debilita la acción colectiva, dificulta la convergencia entre actores e incrementa la presión sobre las instituciones locales. 

30 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

Florida se evidencia como un nodo histórico donde convergen procesos de fortalecimiento de capital humano y producción agrícola; Pradera, Miranda y Corinto como territorios con potencial para encontrarse en dinámicas de vocación agropecuaria, alta organización social y productiva. Con realidades distintas pero interdependientes, impulsar una lógica subregional es pertinente para potenciar los activos territoriales desde la educación, la producción, transformación y la comercialización de alimentos. 

Las **Agendas Ciudadanas** como procesos permanentes de concertación, se especializan por nodos. Mujeres en Miranda, jóvenes en Corinto, instituciones y representantes sectoriales en Pradera, y actores rurales en Florida, logran que el ordenamiento y la visión territorial se construyan desde la base; conectan actores y oportunidades, para gestionar iniciativas de desarrollo, acceder a recursos y reconstruir lazos de confianza. Transitan de acciones aisladas a proyectos estructurados con participación multiactor, orientados al acceso a derechos sociales y productivos. 

La Convergencia impulsa la agricultura familiar como eje articulador de las relaciones comunitarias; fortalece la confianza y facilita el tránsito hacia ejercicios colectivos que amplían la variedad de alimentos producidos, transformados y comercializados. 

El **Centro de Reindustrialización** con dos sedes rurales en Florida, facilita que las unidades productivas vinculadas a circuitos tradicionales como cacao, café y plátano desarrollen productos con valor agregado.  La participación en circuitos locales activa ferias, canastas agroalimentarias y mercados comunitarios, con resultados económicos concretos; se evidencia una mayor capacidad organizativa reflejada en la creación de fondos comunitarios de ahorro que estabilizan los ingresos. 

La Convergencia avanza hacia una transformación sistémica. Logra conectar la producción local con la transformación, la organización y el mercado, en tanto se fortalecen los vínculos sociales y liderazgos que sostienen la autonomía económica y la sostenibilidad territorial. 

## _**Zarzal, Nodo de innovación y participación de las nuevas generaciones**_ 

Avanza con determinación a posicionarse como un territorio clave en la transformación productiva, con el liderazgo de una juventud comprometida con el desarrollo local. Sin embargo, el desafío está en fortalecer la articulación multiactor para dar sostenibilidad a los procesos de transformación y diversificación. 

Impulsamos el proceso colectivo de articulación desde diversos ámbitos. **El Centro de Reindustrialización** , abre nuevas oportunidades para unidades productivas que generan valor agregado, fortalecen sus capacidades técnicas y consolidan encadenamientos empresariales. Complementan el proceso el Semillero de Líderes y la red del Laboratorio de Innovación Empresarial y Social   LIEMSO. Forjan una nueva generación de liderazgos que robustece la base comunitaria y empresarial. Las iniciativas juveniles y empresariales que surgen del proceso, se convierten en palanca de innovación territorial. 

La articulación con la Cámara de Comercio de Tuluá y la Asociación de Empresarios Zarzaleños soporta el avance hacia una cultura de competitividad colaborativa. Los productores no solo gestionan sus unidades familiares, incursionan en modelos de negocio con capacidad de planeación, evaluación de costos, identificación de mercados y posicionamiento diferenciado de sus productos. 

La Agenda Ciudadana se concreta con una participación técnica cada vez más cualificada de jóvenes y asociaciones, que gestionan portafolios diversificados de inversión. La integración de jóvenes en el 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

31 

Consejo Municipal de Juventudes en los espacios de decisión económica permite que las nuevas generaciones tracen de manera directa la ruta de un mejor futuro para ellas y sus territorios. 

Esta Convergencia, desde el fortalecimiento de capacidades, la apertura de oportunidades de valor agregado y la promoción de la participación juvenil, transita hacia una dinámica de gestión territorial colaborativa. 

## **Guachené, Caloto y Santander de Quilichao, autonomía étnica y productiva** 

En esta Convergencia, el desarrollo se concibe desde la coexistencia de una base histórica interétnica y pluricultural, un entramado social productivo y organizativo con alto valor ambiental y cultural, en el marco de la defensa de los derechos étnicos. Estos activos han permitido promover una producción agroalimentaria autónoma, arraigada en las dinámicas propias del territorio. 

En un entorno caracterizado por restricciones estructurales de movilidad y condiciones de seguridad inestables que interrumpen los procesos organizativos y limitan el trabajo en territorio, cada espacio de encuentro requiere más tiempo, mayor coordinación institucional y un proceso constante de construcción de confianza. 

El principal desafío ha sido fortalecer las capacidades locales mientras se tejen alianzas interétnicas sólidas con actores sociales e institucionales, siendo el reto la reducción de la dependencia de apoyos externos para consolidar procesos productivos sostenibles que fortalezcan la autonomía económica y social. En este sentido, hemos impulsado redes territoriales de productores y emprendedores que anclan el desarrollo en las realidades y saberes del norte del Cauca. 

La transformación sistémica es una respuesta vital del territorio a la presión de las economías ilegales y el riesgo del reclutamiento. Iniciativas de desarrollo como la **Escuela de Saberes de la Diáspora** apuestan por la organización, la cultura y la producción, barrera protectora que genera cohesión, sentido de pertenencia y proyectos de vida para las nuevas generaciones. Las familias se articulan al circuito productivo de plátano; la formación técnica y el acompañamiento en la gestión de proyectos, fortalecen sus ingresos y reconstruyen el tejido social fragmentado. Las comunidades se cuidan, organizan y sostienen espacios colectivos donde forjan sus futuros compartidos. 

En este camino, organizaciones como **ASOMUTS** , **ASOPRAU** , la **Red de Jóvenes Sembradores de Agua** y otros productores han sido protagonistas. Evidencian que es posible reconstruir la memoria del territorio en tanto dinamizan procesos en piscicultura, producción de aromáticas, especies menores y transformación textil, blindando la comunidad con autonomía económica. 

Estos resultados comienzan a tejer una transformación. Las economías locales organizadas emergen como núcleos capaces de movilizar recursos, gestionar procesos colectivos y sostener el desarrollo desde el territorio. 

## **Bolívar, Roldanillo, La Unión, Toro y Obando, la educación como puente hacia la asociatividad y la productividad empresarial** 

Esta convergencia surge de la potencialidad de la vocación agrícola de estos territorios, de las capacidades instaladas en las Instituciones Educativas Públicas Rurales a través de 12 años de implementación de la Política de Educación Rural de la Gobernación del Valle. Lograr que esta política pública se instale sistémicamente en la dinámica territorial plantea el reto de superar la desarticulación del tejido social, impulsar la asociatividad y potenciar los encadenamientos productivos que surgen del proceso educativo. 

32 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

En el periodo, concertamos la alianza con la Gobernación del Valle para dar inicio en el 2026 a la integración de la política en los procesos de gestión territorial colaborativa desde el fortalecimiento de las Asociaciones de Futuros Agricultores (AFA) como núcleo de los Semilleros de Liderazgo; acompañando una transformación educativa rural hacia lo productivo agroempresarial. 

El fortalecimiento de las AFA sienta las bases de una gobernanza subregional que las articula a organizaciones de base como FEDEAGRO y el Consejo Subregional de Competitividad e Innovación para integrar a los jóvenes en los espacios de toma de decisiones. 

El objetivo es articular estos activos territoriales con el ímpetu de los Semilleros de Liderazgo y el potencial gastronómico y cultural, para lograr que los jóvenes inicien procesos asociativos con identidad territorial. El resultado es una transición de estudiantes a emprendedores asociados que gestionan iniciativas productivas con estándares de competitividad para que el territorio se soporte en un relevo generacional con capacidades técnicas, de gestión y cooperación. 

## **Logros que soportan las transformaciones** 

## **CONVERGENCIAS TERRITORIALES Y LA AGENDA GLOBAL DE DESARROLLO** 

Las Convergencias Territoriales operan como mecanismo de aceleración para contribuir al logro de los Objetivos de Desarrollo Sostenible (ODS), transformando brechas sociales estructurales en oportunidades de desarrollo sistémico. 

**1. Fin de la Pobreza y Hambre Cero (ODS 1 y 2).** Abordamos la vulnerabilidad multidimensional mediante el fortalecimiento de Sistemas Agroalimentarios Sostenibles. 

**2. Trabajo Decente, Crecimiento Económico y Reducción de Desigualdades (ODS 8 y 10).** Fortalecemos las capacidades técnicas y empresariales de las unidades productivas, impulsamos la competitividad y circuitos locales de comercialización. 

33 

_Este capítulo se encuentra bajo Derecho de Inspección hasta el 25 de marzo de 2026, y tiene algunos datos pendientes de verificación por Auditoría._ 

**3. Equidad de Género y Diversidad (ODS 5 y 10).** Potenciamos el rol de la mujer y las diversidades étnicas como motor de desarrollo.  Promovemos la diversidad de liderazgos de mujeres y jóvenes que reconstruyen visiones de futuro más equitativas y representativas. 

**4. Paz, Justicia e Instituciones Sólidas (ODS 16).** Promovemos la Gobernanza Territorial como base de legitimidad y estabilidad regional. Fomentamos ecosistemas de diálogo y asistencia técnica para el ejercicio de una ciudadanía activa e informada que interactúa con la institucionalidad pública para avanzar conjuntamente hacia un Estado transparente y garante de derechos. 

**5. Alianzas para lograr los Objetivos (ODS 17).** Articulamos el capital relacional y financiero de empresas, gobierno, sector social y sociedad civil, complementariedad que permite movilizar recursos y conocimientos que maximizan el impacto colectivo. 

## **Derechos humanos, inclusión y enfoque diferencial** 

[GRI 412] 

La estrategia incorpora de manera transversal la evaluación de riesgos sociales y de derechos humanos, priorizando territorios con altos índices de pobreza multidimensional, inseguridad alimentaria, informalidad y contextos de conflictividad. 

Este enfoque permite habilitar condiciones de inclusión para el acceso y ejercicio de derechos; acompañamos e impulsamos procesos atemperados a la plurietnia y multiculturalidad de los territorios donde operamos, que habilitan oportunidades para jóvenes, mujeres, población indígena, afrodescendiente y campesina. 

## **7.2.3 Perspectivas 2026** 

Proyectamos una agenda orientada a profundizar las transformaciones en proceso y escalar las contribuciones de la Gestión Territorial Colaborativa 

1. **Profundización de la Meta 2030:** Avanzaremos en la consolidación de las **5 Convergencias Territoriales** , fortaleciendo los procesos de gobernanza para asegurar que las decisiones colectivas sean legítimas y pertinentes. 

2. **Mejora de los Sistemas Agroalimentarios:** Priorizaremos el tránsito hacia la transformación con valor agregado, impulsando una comercialización local que contribuya a la estabilización de los ingresos familiares. 

3. **Innovación Social y Gestión del Conocimiento:** Continuaremos en la profundización del análisis territorial para medir con mayor precisión los cambios en las dinámicas y condiciones de vida. 

4. **Fortalecimiento ciudadano:** Fortaleceremos las redes y organizaciones sociales comunitarias en su gobernanza y capacidad de gestión e incidencia.